# for GCC Compiler (Homebrew)
# Disable USE_GEMMT to build without BLIS (uses reference dskr2k/zskr2k instead)
set(USE_GEMMT OFF CACHE BOOL "Use GEMMT (requires BLIS)" FORCE)

# Auto-detect Homebrew GCC (avoid Apple Clang's /usr/bin/gcc)
execute_process(COMMAND brew --prefix gcc OUTPUT_VARIABLE GCC_PREFIX OUTPUT_STRIP_TRAILING_WHITESPACE)
file(GLOB _gcc_bins "${GCC_PREFIX}/bin/gcc-[0-9]*")
file(GLOB _gxx_bins "${GCC_PREFIX}/bin/g++-[0-9]*")
file(GLOB _gfc_bins "${GCC_PREFIX}/bin/gfortran-[0-9]*")
list(SORT _gcc_bins)
list(SORT _gxx_bins)
list(SORT _gfc_bins)
list(GET _gcc_bins -1 GCC_C_COMPILER)
list(GET _gxx_bins -1 GCC_CXX_COMPILER)
list(GET _gfc_bins -1 GCC_Fortran_COMPILER)
set(CMAKE_C_COMPILER "${GCC_C_COMPILER}" CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER "${GCC_CXX_COMPILER}" CACHE STRING "" FORCE)
set(CMAKE_Fortran_COMPILER "${GCC_Fortran_COMPILER}" CACHE STRING "" FORCE)

set(CMAKE_C_FLAGS_DEBUG "-g -O0 -Wall  -Wformat -Werror=format-security")
set(CMAKE_C_FLAGS_RELEASE "-O3 -Wno-unknown-pragmas ")
set(CMAKE_CXX_FLAGS_RELEASE "-O3 -Wno-unknown-pragmas ")
