from __future__ import print_function

import math
import os
import shutil
import subprocess
import sys

from backflow_def_helper import build_chain_nn_backflow, write_chain_nn_backflow


def copy_base_defs(refdir, workdir):
    for fn in ("modpara.def", "locspn.def", "trans.def", "qptransidx.def"):
        shutil.copy(os.path.join(refdir, fn), os.path.join(workdir, fn))


def write_namelist(workdir, include_backflow):
    lines = [
        "         ModPara  modpara.def",
        "         LocSpin  locspn.def",
        "           Trans  trans.def",
        "        OneBodyG  greenone.def",
        "        TwoBodyG  greentwo.def",
        " OrbitalGeneral  orbitalidxgen.def",
        "        TransSym  qptransidx.def",
    ]
    if include_backflow:
        lines.extend([
            "              BF  bf.def",
            "         BFRange  rangebf.def",
        ])
    with open(os.path.join(workdir, "namelist.def"), "w") as fp:
        fp.write("\n".join(lines) + "\n")


def write_orbital_general(workdir, nsite, complex_type=1, optimize=True):
    nsite2 = 2 * nsite
    norbital = nsite2 * (nsite2 - 1) // 2
    opt_flag = 1 if optimize else 0
    lines = [
        "=============================================",
        "NOrbitalIdx         {}".format(norbital),
        "ComplexType          {}".format(complex_type),
        "=============================================",
        "=============================================",
    ]
    idx = 0
    for orb_i in range(nsite2):
        for orb_j in range(orb_i + 1, nsite2):
            lines.append(
                "{:5d} {:2d} {:6d} {:2d} {:6d}      1".format(
                    orb_i % nsite, orb_i // nsite,
                    orb_j % nsite, orb_j // nsite,
                    idx,
                )
            )
            idx += 1
    for idx in range(norbital):
        lines.append("{:5d}      {}".format(idx, opt_flag))
    with open(os.path.join(workdir, "orbitalidxgen.def"), "w") as fp:
        fp.write("\n".join(lines) + "\n")


def write_green_defs(workdir):
    one_body_rows = [
        (0, 0, 0, 0),
        (0, 0, 1, 0),
        (0, 1, 0, 1),
        (0, 1, 1, 1),
    ]
    with open(os.path.join(workdir, "greenone.def"), "w") as fp:
        fp.write("===============================\n")
        fp.write("NCisAjs         {}\n".format(len(one_body_rows)))
        fp.write("===============================\n")
        fp.write("======== Green functions ======\n")
        fp.write("===============================\n")
        for row in one_body_rows:
            fp.write(" ".join("{:5d}".format(value) for value in row) + "\n")

    two_body_rows = [
        (0, 0, 0, 0, 0, 1, 0, 1),
        (0, 0, 1, 0, 2, 1, 3, 1),
        (0, 1, 1, 1, 2, 0, 3, 0),
    ]
    with open(os.path.join(workdir, "greentwo.def"), "w") as fp:
        fp.write("=============================================\n")
        fp.write("NCisAjsCktAltDC         {}\n".format(len(two_body_rows)))
        fp.write("=============================================\n")
        fp.write("======== Green functions for BF-FSZ ========\n")
        fp.write("=============================================\n")
        for row in two_body_rows:
            fp.write(" ".join("{:5d}".format(value) for value in row) + "\n")


def build_stale_base_two_body_rows(nsite=4):
    general_rows = []
    contracted_rows = []

    # Cover every spin-conserving double hop so at least one general-path term
    # is active for every half-filled sample generated by this fixture.
    for s, t in ((0, 1), (1, 0)):
        for rj in range(nsite):
            for ri in range(nsite):
                if ri == rj:
                    continue
                for rl in range(nsite):
                    for rk in range(nsite):
                        if rk == rl:
                            continue
                        general_rows.append((ri, s, rj, s, rk, t, rl, t))

        # rk == rl dispatches to GreenFunc1BF_fsz after checking the density.
        # Listing all sites and hops guarantees an active contracted term after
        # the last active general term has overwritten global SlaterElmBF.
        for rk in range(nsite):
            for rj in range(nsite):
                for ri in range(nsite):
                    if ri != rj:
                        contracted_rows.append((ri, s, rj, s, rk, t, rk, t))

    return general_rows, contracted_rows


def write_two_body_rows(workdir, rows):
    with open(os.path.join(workdir, "greentwo.def"), "w") as fp:
        fp.write("=============================================\n")
        fp.write("NCisAjsCktAltDC         {}\n".format(len(rows)))
        fp.write("=============================================\n")
        fp.write("======== Green functions for BF-FSZ ========\n")
        fp.write("=============================================\n")
        for row in rows:
            fp.write(" ".join("{:5d}".format(value) for value in row) + "\n")


def replace_data_line(workdir, filename, row):
    path = os.path.join(workdir, filename)
    with open(path) as fp:
        lines = fp.readlines()
    if len(lines) < 6:
        raise RuntimeError("{} has no data row".format(filename))
    lines[5] = row
    with open(path, "w") as fp:
        fp.writelines(lines)


def make_spin_changing_transfer(workdir):
    replace_data_line(
        workdir,
        "trans.def",
        "    1     0     0     1         1.000000000000000         0.000000000000000\n",
    )


def make_spin_changing_one_body_g(workdir):
    replace_data_line(
        workdir,
        "greenone.def",
        "    0     0     1     1\n",
    )


def make_spin_changing_two_body_g(workdir):
    replace_data_line(
        workdir,
        "greentwo.def",
        "    0     0     0     1     0     1     0     1\n",
    )


def make_spin_changing_two_body_g_ex(workdir):
    rows = [
        (0, 0, 1, 1, 2, 0, 3, 0),
    ]
    with open(os.path.join(workdir, "greentwoex.def"), "w") as fp:
        fp.write("=============================================\n")
        fp.write("NCisAjsCktAlt         {}\n".format(len(rows)))
        fp.write("=============================================\n")
        fp.write("======== Green functions for BF-FSZ ========\n")
        fp.write("=============================================\n")
        for row in rows:
            fp.write(" ".join("{:5d}".format(value) for value in row) + "\n")

    namelist_path = os.path.join(workdir, "namelist.def")
    with open(namelist_path) as fp:
        lines = fp.readlines()
    if not any(line.split() and line.split()[0] == "TwoBodyGEx" for line in lines):
        lines.append("      TwoBodyGEx  greentwoex.def\n")
    with open(namelist_path, "w") as fp:
        fp.writelines(lines)


def make_momentum_projection(workdir):
    with open(os.path.join(workdir, "qptransidx.def"), "w") as fp:
        fp.write("=============================================\n")
        fp.write("NQPTrans          2\n")
        fp.write("=============================================\n")
        fp.write("======== TrIdx_TrWeight_and_TrIdx_i_xi ======\n")
        fp.write("=============================================\n")
        fp.write("0    1.00000    0.00000\n")
        fp.write("1    1.00000    0.00000\n")
        fp.write("    0      0      0      1\n")
        fp.write("    0      1      1      1\n")
        fp.write("    0      2      2      1\n")
        fp.write("    0      3      3      1\n")
        fp.write("    1      0      1      1\n")
        fp.write("    1      1      2      1\n")
        fp.write("    1      2      3      1\n")
        fp.write("    1      3      0      1\n")


def write_locspn(workdir, local_sites, nsite=4):
    local_sites = set(local_sites)
    with open(os.path.join(workdir, "locspn.def"), "w") as fp:
        fp.write("================================\n")
        fp.write("NlocalSpin     {}\n".format(len(local_sites)))
        fp.write("================================\n")
        fp.write("========i_1LocSpn_0IteElc ======\n")
        fp.write("================================\n")
        for site in range(nsite):
            fp.write("{:5d} {:6d}\n".format(site, 1 if site in local_sites else 0))


def update_modpara(workdir, updates):
    path = os.path.join(workdir, "modpara.def")
    found = set()
    lines = []
    with open(path) as fp:
        for line in fp:
            cols = line.split()
            if cols and cols[0] in updates:
                lines.append("{:<15} {}\n".format(cols[0], updates[cols[0]]))
                found.add(cols[0])
            else:
                lines.append(line)
    for key, value in updates.items():
        if key not in found:
            lines.append("{:<15} {}\n".format(key, value))
    with open(path, "w") as fp:
        fp.writelines(lines)


def parse_norbitalidx(path):
    with open(path) as fp:
        for line in fp:
            cols = line.split()
            if len(cols) >= 2 and cols[0] == "NOrbitalIdx":
                return int(cols[1])
    raise RuntimeError("NOrbitalIdx was not found in {}".format(path))


def write_nonidentity_init_parameter(path, nprojbf, nslater):
    projbf_values = [
        0.93, 0.08, -0.05, 0.035, -0.025,
        0.015, -0.012, 0.010, -0.007, 0.005,
    ]
    if nprojbf < 2:
        raise RuntimeError("non-identity BackFlow test requires at least two ProjBF parameters")

    values = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    for idx in range(nprojbf):
        real = projbf_values[idx] if idx < len(projbf_values) else 0.001 / float(idx + 1)
        values.extend([real, 0.0, 0.0])
    matrix_width = int(round(math.sqrt(nslater)))
    for idx in range(nslater):
        if matrix_width * matrix_width == nslater:
            row = idx // matrix_width
            col = idx % matrix_width
            real = 1.0 + 0.1 * row if row == col else 0.03 * float(row - col)
        else:
            real = math.sin(0.37 * (idx + 1))
        values.extend([real, 0.0, 0.0])

    with open(path, "w") as fp:
        fp.write(" ".join("{:.18e}".format(value) for value in values))
        fp.write("\n")


def write_nonidentity_init(workdir, nsite=4):
    definition = build_chain_nn_backflow(length=nsite, optimize=False)
    nslater = parse_norbitalidx(os.path.join(workdir, "orbitalidxgen.def"))
    init_name = "nonidentity_init.dat"
    write_nonidentity_init_parameter(
        os.path.join(workdir, init_name),
        definition.n_proj_bf,
        nslater,
    )
    return init_name


def run_vmc(rootdir, workdir, mpi_procs=None, init_path=None, extra_env=None):
    bin_to_test = os.path.join(rootdir, "..", "..", "src", "mVMC", "vmc.out")
    cmd = [bin_to_test, "-e", "namelist.def"]
    if init_path is not None:
        cmd.append(init_path)
    if mpi_procs:
        mpi_args = os.environ.get("MVMC_MPI_ARGS", "").split()
        cmd = ["mpirun"] + mpi_args + ["-np", mpi_procs] + cmd
    env = os.environ.copy()
    if extra_env is not None:
        env.update(extra_env)
    proc = subprocess.run(
        cmd,
        cwd=workdir,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    with open(os.path.join(workdir, "vmc.log"), "w") as fp:
        fp.write(proc.stdout)
    return proc


def read_first_row(path):
    with open(path) as fp:
        for line in fp:
            cols = line.split()
            if cols:
                return [float(x) for x in cols]
    raise RuntimeError("no numeric row in {}".format(path))


def read_float_rows(path):
    rows = []
    with open(path) as fp:
        for line in fp:
            cols = line.split()
            if cols:
                rows.append([float(x) for x in cols])
    return rows


def read_flat_floats(path):
    values = []
    with open(path) as fp:
        for line in fp:
            values.extend(float(x) for x in line.split())
    return values


def read_child_opt_rows(path):
    rows = []
    with open(path) as fp:
        for line in fp:
            cols = line.split()
            if len(cols) < 3:
                continue
            try:
                idx = int(cols[0])
                real = float(cols[1])
                imag = float(cols[2])
            except ValueError:
                continue
            rows.append((idx, real, imag))
    return rows


def read_key_values(path):
    values = {}
    with open(path) as fp:
        for line in fp:
            cols = line.split()
            if len(cols) >= 2:
                values[cols[0]] = cols[1:]
    return values


def read_bffsz_profile_stats(path, source, kind):
    marker = "BF-FSZ {} {} stats".format(source, kind)
    with open(path) as fp:
        for line in fp:
            if marker not in line:
                continue
            fields = {}
            for token in line.split():
                if "=" in token:
                    key, value = token.split("=", 1)
                    fields[key] = value
            if not all(key in fields for key in ("calls", "mean", "max")):
                break
            return int(fields["calls"]), float(fields["mean"]), int(fields["max"])
    raise RuntimeError("{} was not found in {}".format(marker, path))


def read_bffsz_profile_hist_sum(path, source, kind):
    marker = "BF-FSZ {} {}".format(source, kind)
    with open(path) as fp:
        for line in fp:
            if marker not in line:
                continue
            values = []
            for token in line.split():
                if ":" not in token:
                    continue
                try:
                    values.append(int(token.rsplit(":", 1)[1]))
                except ValueError:
                    pass
            if values:
                return sum(values)
    raise RuntimeError("{} was not found in {}".format(marker, path))


def read_bffsz_pf_paths(path, source):
    marker = "BF-FSZ {} Pfaffian paths".format(source)
    with open(path) as fp:
        for line in fp:
            if marker not in line:
                continue
            values = {}
            for token in line.split():
                if ":" not in token:
                    continue
                key, value = token.rsplit(":", 1)
                try:
                    values[key] = int(value)
                except ValueError:
                    pass
            if all(key in values for key in ("optimized", "direct-full", "fallback")):
                return values
    raise RuntimeError("{} was not found in {}".format(marker, path))


def get_float(values, key):
    if key not in values:
        raise RuntimeError("{} was not found in dump".format(key))
    return float(values[key][0])


def get_int(values, key):
    if key not in values:
        raise RuntimeError("{} was not found in dump".format(key))
    return int(values[key][0])


def assert_finite_nonzero_rows(path, label):
    rows = read_float_rows(path)
    if not rows:
        print("ERROR: {} output is empty.".format(label))
        return -1
    max_abs = 0.0
    for row in rows:
        for value in row:
            if not math.isfinite(value):
                print("ERROR: {} output contains non-finite values.".format(label))
                return -1
            max_abs = max(max_abs, abs(value))
    if max_abs <= 1.0e-12:
        print("ERROR: {} output is vacuous: all values are zero.".format(label))
        return -1
    return 0


def assert_finite_values(values, label):
    if not values:
        print("ERROR: {} is empty.".format(label))
        return -1
    for value in values:
        if not math.isfinite(value):
            print("ERROR: {} contains non-finite values.".format(label))
            return -1
    return 0


def assert_child_opt_file(workdir, filename, expected_rows, zqp_group_offset, label):
    child_path = os.path.join(workdir, "output", filename)
    if not os.path.exists(child_path):
        print("ERROR: {} was not created.".format(filename))
        return -1
    rows = read_child_opt_rows(child_path)
    if len(rows) != expected_rows:
        print("ERROR: {} row count mismatch: got {}, expected {}".format(
            filename, len(rows), expected_rows))
        return -1
    zqp_path = os.path.join(workdir, "output", "zqp_opt.dat")
    zqp_values = read_flat_floats(zqp_path)
    for local_idx, real, imag in rows:
        if local_idx < 0 or local_idx >= expected_rows:
            print("ERROR: {} has invalid local index {}".format(filename, local_idx))
            return -1
        if not (math.isfinite(real) and math.isfinite(imag)):
            print("ERROR: {} contains non-finite values.".format(filename))
            return -1
        group = zqp_group_offset + local_idx
        zqp_pos = 3 * group
        if zqp_pos + 1 >= len(zqp_values):
            print("ERROR: zqp_opt.dat is too short for {} group {}".format(label, group))
            return -1
        if max(abs(real - zqp_values[zqp_pos]), abs(imag - zqp_values[zqp_pos + 1])) > 1.0e-12:
            print("ERROR: {} does not match zqp_opt.dat at row {}".format(filename, local_idx))
            return -1
    return 0


def read_orbital_opt_rows(workdir):
    return read_child_opt_rows(os.path.join(workdir, "output", "zqp_orbital_general_opt.dat"))


def compare_child_rows(left, right, tolerance, label):
    if len(left) != len(right):
        print("ERROR: {} row count mismatch: left={} right={}".format(label, len(left), len(right)))
        return -1
    max_diff = 0.0
    for (li, lr, lii), (ri, rr, rii) in zip(left, right):
        if li != ri:
            print("ERROR: {} local index mismatch: left={} right={}".format(label, li, ri))
            return -1
        max_diff = max(max_diff, abs(lr - rr), abs(lii - rii))
    if max_diff > tolerance:
        print("ERROR: {} mismatch: max_abs_diff={:.3e}".format(label, max_diff))
        return -1
    return 0


def max_abs_diff(left_rows, right_rows):
    if len(left_rows) != len(right_rows):
        raise RuntimeError("row count mismatch: left={} right={}".format(len(left_rows), len(right_rows)))
    max_diff = 0.0
    for left, right in zip(left_rows, right_rows):
        if len(left) != len(right):
            raise RuntimeError("column count mismatch: left={} right={}".format(len(left), len(right)))
        for x, y in zip(left, right):
            max_diff = max(max_diff, abs(x-y))
    return max_diff


def prepare_case(rootdir, name, include_backflow, orbital_complex_type=1,
                 orbital_optimize=True, backflow_optimize=False):
    refdir = os.path.join(rootdir, "data", "BackFlow_Identity_Complex")
    workdir = os.path.join(rootdir, "work", name)
    if os.path.exists(workdir):
        shutil.rmtree(workdir)
    os.makedirs(workdir)

    copy_base_defs(refdir, workdir)
    write_namelist(workdir, include_backflow)
    write_orbital_general(
        workdir,
        nsite=4,
        complex_type=orbital_complex_type,
        optimize=orbital_optimize,
    )
    write_green_defs(workdir)
    if include_backflow:
        write_chain_nn_backflow(workdir, length=4, optimize=backflow_optimize)
    return workdir


def run_twobody_stale_base_case(rootdir, case_name, mpi_procs=None):
    pf_update_cases = {
        "BackFlow_FSZ_PfUpdate_NonIdentity_Complex": "optimized",
        "BackFlow_FSZ_PfUpdate_NonIdentity_Complex_mpi": "optimized",
        "BackFlow_FSZ_PfUpdate_MoreRanks_NonIdentity_Complex_mpi": "optimized",
        "BackFlow_FSZ_PfUpdate_Fallback_NonIdentity_Complex": "fallback",
        "BackFlow_FSZ_PfUpdate_ExactZeroFallback_NonIdentity_Complex": "exact-zero",
        "BackFlow_FSZ_PfUpdate_LapackFallback_NonIdentity_Complex": "lapack",
        "BackFlow_FSZ_PfUpdate_DirectFull_NonIdentity_Complex": "direct-full",
        "BackFlow_FSZ_PfUpdate_PermutedLabels_NonIdentity_Complex": "permuted",
        "BackFlow_FSZ_PfUpdate_ExplicitState_NonIdentity_Complex": "explicit-state",
        "BackFlow_FSZ_PfUpdate_InvalidArguments_NonIdentity_Complex": "arguments",
    }
    affected_cases = (
        "BackFlow_FSZ_AffectedRows_NonIdentity_Complex",
        "BackFlow_FSZ_AffectedRows_NonIdentity_Complex_mpi",
    ) + tuple(pf_update_cases)
    if case_name != "BackFlow_FSZ_TwoBodyG_StaleBase_NonIdentity_Complex" \
            and case_name not in affected_cases:
        return None

    general_rows, contracted_rows = build_stale_base_two_body_rows()
    ordered_rows = general_rows + contracted_rows
    reference_rows = contracted_rows + general_rows
    reference_case_rows = reference_rows
    if case_name in pf_update_cases and pf_update_cases[case_name] == "permuted":
        reference_case_rows = ordered_rows

    ordered_workdir = prepare_case(rootdir, case_name, True)
    reference_workdir = prepare_case(rootdir, case_name + "_reference", True)
    for workdir, rows in (
        (ordered_workdir, ordered_rows),
        (reference_workdir, reference_case_rows),
    ):
        update_modpara(workdir, {"NVMCSample": "1"})
        if case_name in affected_cases:
            update_modpara(workdir, {"NMPTrans": "2"})
            make_momentum_projection(workdir)
        write_two_body_rows(workdir, rows)

    ordered_init = write_nonidentity_init(ordered_workdir)
    reference_init = write_nonidentity_init(reference_workdir)
    ordered_env = {
        "MVMC_BF_FSZ_GREEN_REBUILD_CHECK": "1",
        "MVMC_BF_FSZ_AFFECTED_CHECK": "1",
        "MVMC_BF_PROFILE": "1",
    }
    if case_name in pf_update_cases:
        ordered_env["MVMC_BF_FSZ_PF_UPDATE_CHECK"] = "1"
        if pf_update_cases[case_name] == "fallback":
            ordered_env["MVMC_BF_FSZ_PF_UPDATE_FORCE_FALLBACK"] = "1"
        elif pf_update_cases[case_name] == "exact-zero":
            ordered_env["MVMC_BF_FSZ_PF_UPDATE_INJECT_STATUS"] = "1"
        elif pf_update_cases[case_name] == "lapack":
            ordered_env["MVMC_BF_FSZ_PF_UPDATE_INJECT_STATUS"] = "2"
        elif pf_update_cases[case_name] == "direct-full":
            ordered_env["MVMC_BF_FSZ_PF_UPDATE_KFULL"] = "1"
        elif pf_update_cases[case_name] == "permuted":
            ordered_env["MVMC_BF_FSZ_PERMUTE_PARTICLE_LABELS"] = "1"
        elif pf_update_cases[case_name] == "explicit-state":
            ordered_env["MVMC_BF_FSZ_PF_UPDATE_EXPLICIT_STATE_CHECK"] = "1"
        elif pf_update_cases[case_name] == "arguments":
            ordered_env["MVMC_BF_FSZ_PF_UPDATE_ARGUMENT_CHECK"] = "1"
    ordered_proc = run_vmc(
        rootdir,
        ordered_workdir,
        mpi_procs=mpi_procs,
        init_path=ordered_init,
        extra_env=ordered_env,
    )
    if ordered_proc.returncode != 0:
        print(ordered_proc.stdout)
        return ordered_proc.returncode

    reference_env = None
    if case_name in pf_update_cases and pf_update_cases[case_name] == "permuted":
        reference_env = {
            "MVMC_BF_FSZ_PERMUTE_PARTICLE_LABELS": "1",
            "MVMC_BF_FSZ_PF_UPDATE_KFULL": "1",
        }
    reference_proc = run_vmc(
        rootdir,
        reference_workdir,
        mpi_procs=mpi_procs,
        init_path=reference_init,
        extra_env=reference_env,
    )
    if reference_proc.returncode != 0:
        print(reference_proc.stdout)
        return reference_proc.returncode

    timer_path = os.path.join(ordered_workdir, "output", "zvo_CalcTimer.dat")
    for source in ("sample", "green"):
        changed_calls, changed_mean, changed_max = read_bffsz_profile_stats(
            timer_path, source, "changed")
        affected_calls, affected_mean, affected_max = read_bffsz_profile_stats(
            timer_path, source, "affected")
        if changed_calls <= 0 or affected_calls != changed_calls:
            print("ERROR: BF-FSZ {} affected profile call mismatch".format(source))
            return -1
        if changed_mean <= 0.0 or changed_max <= 0 or changed_max > 8:
            print("ERROR: BF-FSZ {} changed profile is invalid".format(source))
            return -1
        if affected_mean < 1.0 or affected_max < 1 or affected_max > 4:
            print("ERROR: BF-FSZ {} affected profile is invalid".format(source))
            return -1
        for hist_kind in ("changed hist", "affected hist", "affected ratio hist"):
            if read_bffsz_profile_hist_sum(timer_path, source, hist_kind) != changed_calls:
                print("ERROR: BF-FSZ {} {} count mismatch".format(source, hist_kind))
                return -1

        if case_name in pf_update_cases:
            paths = read_bffsz_pf_paths(timer_path, source)
            mode = pf_update_cases[case_name]
            if mode in ("optimized", "permuted", "explicit-state", "arguments"):
                if paths["optimized"] <= 0 or paths["fallback"] != 0:
                    print("ERROR: BF-FSZ {} optimized Pfaffian path was not isolated".format(source))
                    return -1
            elif mode in ("fallback", "exact-zero", "lapack"):
                if paths["fallback"] <= 0 or paths["optimized"] != 0:
                    print("ERROR: BF-FSZ {} fallback Pfaffian path was not isolated".format(source))
                    return -1
            elif mode == "direct-full":
                if paths["direct-full"] <= 0 or paths["optimized"] != 0 \
                        or paths["fallback"] != 0:
                    print("ERROR: BF-FSZ {} direct-full Pfaffian path was not isolated".format(source))
                    return -1

    if case_name in pf_update_cases and pf_update_cases[case_name] == "permuted":
        return assert_finite_nonzero_rows(
            os.path.join(ordered_workdir, "output", "zvo_cisajs_001.dat"),
            "permuted-label Pfaffian update",
        )

    ordered_path = os.path.join(ordered_workdir, "output", "zvo_cisajscktalt_001.dat")
    reference_path = os.path.join(reference_workdir, "output", "zvo_cisajscktalt_001.dat")
    ordered_values = read_float_rows(ordered_path)
    reference_values = read_float_rows(reference_path)
    if len(ordered_values) != len(ordered_rows) or len(reference_values) != len(reference_rows):
        print("ERROR: stale-base TwoBodyG output row count mismatch")
        return -1

    ordered_by_term = dict(zip(ordered_rows, ordered_values))
    reference_by_term = dict(zip(reference_case_rows, reference_values))
    diff = max_abs_diff(
        [ordered_by_term[row] for row in ordered_rows],
        [reference_by_term[row] for row in ordered_rows],
    )
    if diff > 1.0e-12:
        print("ERROR: BF-FSZ TwoBodyG depends on general/contracted term order: "
              "max_abs_diff={:.3e}".format(diff))
        return -1

    return assert_finite_nonzero_rows(ordered_path, "stale-base TwoBodyG")


def run_sr_diff_case(rootdir, case_name, mpi_procs=None):
    sr_diff_cases = {
        "BackFlow_FSZ_SRDiff_Identity_Complex": (False, False, True),
        "BackFlow_FSZ_SRDiff_Identity_Complex_mpi": (False, False, True),
        "BackFlow_FSZ_SRDiff_MomentumProjection_Complex": (True, False, True),
        "BackFlow_FSZ_SRDiff_NonIdentity_Complex": (False, True, False),
        "BackFlow_FSZ_SRDiff_MomentumProjection_NonIdentity_Complex": (True, True, False),
    }
    if case_name not in sr_diff_cases:
        return None

    use_momentum, use_nonidentity, check_identity = sr_diff_cases[case_name]
    workdir = prepare_case(rootdir, case_name, True)
    update_modpara(workdir, {"NVMCSample": "1"})
    if use_momentum:
        update_modpara(workdir, {"NMPTrans": "2"})
        make_momentum_projection(workdir)
    init_path = write_nonidentity_init(workdir) if use_nonidentity else None
    dump_path = os.path.join(workdir, "bf_fsz_sr_diff.dat")
    proc = run_vmc(
        rootdir,
        workdir,
        mpi_procs=mpi_procs,
        init_path=init_path,
        extra_env={"MVMC_BF_FSZ_SR_DIFF_DUMP": dump_path},
    )
    if proc.returncode != 0:
        print(proc.stdout)
        return proc.returncode
    if not os.path.exists(dump_path):
        print("ERROR: BF-FSZ SR diff dump was not created")
        return -1

    values = read_key_values(dump_path)
    if get_int(values, "info_bf") != 0:
        print("ERROR: BF-FSZ SR diff base calculation failed")
        return -1
    if get_int(values, "fd_fail_count") != 0:
        print("ERROR: BF-FSZ SR diff finite differences failed")
        print(open(dump_path).read())
        return -1
    if get_int(values, "nan_count") != 0:
        print("ERROR: BF-FSZ SR diff dump contains non-finite values")
        print(open(dump_path).read())
        return -1
    if get_int(values, "nonzero_projbf_fd_count") <= 0:
        print("ERROR: BF-FSZ ProjBF finite difference was vacuous")
        print(open(dump_path).read())
        return -1
    if get_int(values, "nonzero_orbital_fd_count") <= 0:
        print("ERROR: BF-FSZ orbital finite difference was vacuous")
        print(open(dump_path).read())
        return -1

    projbf_diff = get_float(values, "max_abs_projbf_fd_diff")
    orbital_diff = get_float(values, "max_abs_orbital_fd_diff")
    if projbf_diff > 1.0e-8:
        print("ERROR: BF-FSZ ProjBF finite-difference mismatch: {:.3e}".format(projbf_diff))
        print(open(dump_path).read())
        return -1
    if orbital_diff > 1.0e-8:
        print("ERROR: BF-FSZ orbital finite-difference mismatch: {:.3e}".format(orbital_diff))
        print(open(dump_path).read())
        return -1
    if check_identity:
        if get_int(values, "info_no_bf") != 0:
            print("ERROR: BF-FSZ SR diff NoBF reference calculation failed")
            print(open(dump_path).read())
            return -1
        identity_diff = get_float(values, "max_abs_identity_orbital_diff")
        if identity_diff > 1.0e-10:
            print("ERROR: BF-FSZ identity orbital O mismatch: {:.3e}".format(identity_diff))
            print(open(dump_path).read())
            return -1
    return 0


def optimization_modpara_updates(nstore=0, nsrcg=0, nsplit=1, samples=16):
    updates = {
        "NVMCCalMode": "0",
        "NSROptItrStep": "2",
        "NSROptItrSmp": "2",
        "NVMCSample": str(samples),
        "NVMCWarmUp": "4",
        "DSROptRedCut": "1.0e-10",
        "DSROptStaDel": "1.0e-2",
        "DSROptStepDt": "1.0e-2",
        "NStore": str(nstore),
        "NSRCG": str(nsrcg),
        "NSplitSize": str(nsplit),
    }
    if nsrcg != 0:
        updates["NSRCGFallback"] = "1"
        updates["NSRCGAbortOnFail"] = "0"
    return updates


def prepare_optimization_case(rootdir, name, include_backflow=True, orbital_complex_type=1,
                              orbital_optimize=True, backflow_optimize=False,
                              momentum_projection=False, nstore=0, nsrcg=0,
                              nsplit=1, samples=16):
    workdir = prepare_case(
        rootdir,
        name,
        include_backflow,
        orbital_complex_type=orbital_complex_type,
        orbital_optimize=orbital_optimize,
        backflow_optimize=backflow_optimize,
    )
    update_modpara(workdir, optimization_modpara_updates(nstore, nsrcg, nsplit, samples))
    if momentum_projection:
        update_modpara(workdir, {"NMPTrans": "2"})
        make_momentum_projection(workdir)
    return workdir


def assert_optimization_outputs(workdir, include_backflow):
    zqp_path = os.path.join(workdir, "output", "zqp_opt.dat")
    if not os.path.exists(zqp_path):
        print("ERROR: zqp_opt.dat was not created.")
        return -1
    status = assert_finite_values(read_flat_floats(zqp_path), "zqp_opt.dat")
    if status != 0:
        return status

    nslater = parse_norbitalidx(os.path.join(workdir, "orbitalidxgen.def"))
    nprojbf = build_chain_nn_backflow(length=4, optimize=False).n_proj_bf if include_backflow else 0
    expected_zqp_groups = 2 + nprojbf + nslater
    zqp_values = read_flat_floats(zqp_path)
    if len(zqp_values) != 3 * expected_zqp_groups:
        print("ERROR: zqp_opt.dat length mismatch: got {} values, expected {}".format(
            len(zqp_values), 3 * expected_zqp_groups))
        return -1
    if include_backflow:
        status = assert_child_opt_file(
            workdir,
            "zqp_bf_opt.dat",
            nprojbf,
            2,
            "ProjBF opt block",
        )
        if status != 0:
            return status
    return assert_child_opt_file(
        workdir,
        "zqp_orbital_general_opt.dat",
        nslater,
        2 + nprojbf,
        "OrbitalGeneral opt block",
    )


def run_positive_optimization_case(rootdir, case_name, mpi_procs, options):
    prep_options = dict(options)
    prep_options.pop("compare_no_bf", None)
    prep_options.pop("compare_direct_bf", None)
    workdir = prepare_optimization_case(rootdir, case_name, **prep_options)
    proc = run_vmc(rootdir, workdir, mpi_procs)
    if proc.returncode != 0:
        print(proc.stdout)
        return proc.returncode
    status = assert_optimization_outputs(workdir, include_backflow=True)
    if status != 0:
        return status

    if options.get("compare_no_bf", False):
        no_bf_options = dict(options)
        no_bf_options.pop("compare_no_bf", None)
        no_bf_options.pop("compare_direct_bf", None)
        no_bf_options["include_backflow"] = False
        no_bf_options["backflow_optimize"] = False
        no_bf_workdir = prepare_optimization_case(
            rootdir,
            case_name + "_nobf_opt_ref",
            **no_bf_options
        )
        no_bf_proc = run_vmc(rootdir, no_bf_workdir, mpi_procs)
        if no_bf_proc.returncode != 0:
            print(no_bf_proc.stdout)
            return no_bf_proc.returncode
        status = assert_optimization_outputs(no_bf_workdir, include_backflow=False)
        if status != 0:
            return status
        status = compare_child_rows(
            read_orbital_opt_rows(workdir),
            read_orbital_opt_rows(no_bf_workdir),
            1.0e-8,
            "BF-FSZ identity orbital optimization",
        )
        if status != 0:
            return status

    if options.get("compare_direct_bf", False):
        ref_options = dict(options)
        ref_options.pop("compare_no_bf", None)
        ref_options.pop("compare_direct_bf", None)
        ref_options["nstore"] = 0
        ref_options["nsrcg"] = 0
        ref_workdir = prepare_optimization_case(
            rootdir,
            case_name + "_direct_ref",
            **ref_options
        )
        ref_proc = run_vmc(rootdir, ref_workdir, mpi_procs)
        if ref_proc.returncode != 0:
            print(ref_proc.stdout)
            return ref_proc.returncode
        status = assert_optimization_outputs(ref_workdir, include_backflow=True)
        if status != 0:
            return status
        status = compare_child_rows(
            read_orbital_opt_rows(workdir),
            read_orbital_opt_rows(ref_workdir),
            1.0e-8,
            "stored-O BF-FSZ orbital optimization",
        )
        if status != 0:
            return status

    return 0


def run_all_fixed_invalid_case(rootdir, case_name, mpi_procs):
    workdir = prepare_optimization_case(
        rootdir,
        case_name,
        include_backflow=True,
        orbital_complex_type=1,
        orbital_optimize=False,
        backflow_optimize=False,
        nstore=0,
        nsrcg=0,
    )
    proc = run_vmc(rootdir, workdir, mpi_procs)
    expected = "BackFlow FSZ optimization requires at least one optimized variational parameter"
    if proc.returncode == 0:
        print("ERROR: {} unexpectedly succeeded".format(case_name))
        return -1
    if expected not in proc.stdout:
        print("ERROR: {} did not report expected error: {}".format(case_name, expected))
        print(proc.stdout)
        return -1
    if "Start: Optimize VMC parameters." in proc.stdout:
        print("ERROR: {} reached optimization loop before failing".format(case_name))
        print(proc.stdout)
        return -1
    return 0


def run_nsplit_optimization_case(rootdir, case_name, mpi_procs):
    split_ranks = int(mpi_procs) if mpi_procs else 4
    if split_ranks < 4:
        split_ranks = 4
    ref_ranks = max(1, split_ranks // 2)
    split_workdir = prepare_optimization_case(
        rootdir,
        case_name,
        include_backflow=True,
        nstore=1,
        nsrcg=0,
        nsplit=2,
    )
    split_proc = run_vmc(rootdir, split_workdir, str(split_ranks))
    if split_proc.returncode != 0:
        print(split_proc.stdout)
        return split_proc.returncode
    status = assert_optimization_outputs(split_workdir, include_backflow=True)
    if status != 0:
        return status

    ref_workdir = prepare_optimization_case(
        rootdir,
        case_name + "_ref",
        include_backflow=True,
        nstore=1,
        nsrcg=0,
        nsplit=1,
    )
    ref_proc = run_vmc(rootdir, ref_workdir, str(ref_ranks))
    if ref_proc.returncode != 0:
        print(ref_proc.stdout)
        return ref_proc.returncode
    status = assert_optimization_outputs(ref_workdir, include_backflow=True)
    if status != 0:
        return status
    return compare_child_rows(
        read_orbital_opt_rows(split_workdir),
        read_orbital_opt_rows(ref_workdir),
        1.0e-8,
        "NSplitSize BF-FSZ orbital optimization",
    )


def run_optimization_case(rootdir, case_name, mpi_procs=None):
    optimization_cases = {
        "BackFlow_FSZ_Optimization_Identity_Complex": {
            "orbital_complex_type": 1,
            "compare_no_bf": True,
        },
        "BackFlow_FSZ_Optimization_Identity_Complex_mpi": {
            "orbital_complex_type": 1,
            "compare_no_bf": True,
        },
        "BackFlow_FSZ_Optimization_Identity_Real": {
            "orbital_complex_type": 0,
            "compare_no_bf": True,
        },
        "BackFlow_FSZ_Optimization_MomentumProjection_Complex": {
            "orbital_complex_type": 1,
            "momentum_projection": True,
            "compare_no_bf": True,
        },
        "BackFlow_FSZ_Optimization_MomentumProjection_Complex_mpi": {
            "orbital_complex_type": 1,
            "momentum_projection": True,
            "compare_no_bf": True,
        },
        "BackFlow_FSZ_Optimization_BackFlowParams_Complex": {
            "orbital_complex_type": 1,
            "backflow_optimize": True,
        },
        "BackFlow_FSZ_Optimization_StoredO_Complex": {
            "orbital_complex_type": 1,
            "nstore": 1,
            "compare_direct_bf": True,
        },
        "BackFlow_FSZ_Optimization_SRCG_Complex": {
            "orbital_complex_type": 1,
            "nstore": 1,
            "nsrcg": 1,
        },
    }
    if case_name == "BackFlow_FSZ_Optimization_AllFixed_Invalid":
        return run_all_fixed_invalid_case(rootdir, case_name, mpi_procs)
    if case_name == "BackFlow_FSZ_Optimization_NSplitSize_mpi":
        return run_nsplit_optimization_case(rootdir, case_name, mpi_procs)
    if case_name not in optimization_cases:
        return None

    options = {
        "include_backflow": True,
        "orbital_complex_type": 1,
        "orbital_optimize": True,
        "backflow_optimize": False,
        "momentum_projection": False,
        "nstore": 0,
        "nsrcg": 0,
        "nsplit": 1,
        "samples": 16,
    }
    options.update(optimization_cases[case_name])
    return run_positive_optimization_case(rootdir, case_name, mpi_procs, options)


def expect_invalid(rootdir, name, updates, expected, mpi_procs=None, local_sites=None, mutate_defs=None):
    workdir = prepare_case(rootdir, name, True)
    update_modpara(workdir, updates)
    if local_sites is not None:
        write_locspn(workdir, local_sites)
    if mutate_defs is not None:
        mutate_defs(workdir)
    proc = run_vmc(rootdir, workdir, mpi_procs)
    if proc.returncode == 0:
        print("ERROR: {} unexpectedly succeeded".format(name))
        return -1
    if expected not in proc.stdout:
        print("ERROR: {} did not report expected error: {}".format(name, expected))
        print(proc.stdout)
        return -1
    if "Start: Sampling." in proc.stdout:
        print("ERROR: {} reached sampling before failing".format(name))
        print(proc.stdout)
        return -1
    return 0


def get_named_invalid_case(case_name):
    invalid_cases = {
        "BackFlow_FSZ_InvalidSpinChangingTransfer": (
            {},
            "BackFlow FSZ supports only spin-conserving Transfer terms",
            None,
            make_spin_changing_transfer,
        ),
        "BackFlow_FSZ_InvalidSpinChangingOneBodyG": (
            {},
            "BackFlow FSZ supports only spin-conserving OneBodyG terms",
            None,
            make_spin_changing_one_body_g,
        ),
        "BackFlow_FSZ_InvalidSpinChangingOneBodyG_mpi": (
            {},
            "BackFlow FSZ supports only spin-conserving OneBodyG terms",
            None,
            make_spin_changing_one_body_g,
        ),
        "BackFlow_FSZ_InvalidSpinChangingTwoBodyG": (
            {},
            "BackFlow FSZ supports only spin-conserving TwoBodyG terms",
            None,
            make_spin_changing_two_body_g,
        ),
        "BackFlow_FSZ_InvalidSpinChangingTwoBodyGEx": (
            {},
            "including entries derived from TwoBodyGEx",
            None,
            make_spin_changing_two_body_g_ex,
        ),
    }
    return invalid_cases.get(case_name)


def main():
    case_name = sys.argv[1] if len(sys.argv) > 1 else "BackFlow_FSZ_IdentityEnergy_Complex"
    rootdir = os.getcwd()
    mpi_procs = os.environ.get("MVMC_MPI_PROCS")
    momentum_projection_cases = (
        "BackFlow_FSZ_MomentumProjection_Complex",
        "BackFlow_FSZ_MomentumProjection_Complex_mpi",
        "BackFlow_FSZ_MomentumProjection_NonIdentity_Complex",
    )
    nonidentity_momentum_case = case_name == "BackFlow_FSZ_MomentumProjection_NonIdentity_Complex"
    named_invalid = get_named_invalid_case(case_name)
    stale_base_status = run_twobody_stale_base_case(rootdir, case_name, mpi_procs)
    if stale_base_status is not None:
        return stale_base_status
    sr_diff_status = run_sr_diff_case(rootdir, case_name, mpi_procs)
    if sr_diff_status is not None:
        return sr_diff_status
    optimization_status = run_optimization_case(rootdir, case_name, mpi_procs)
    if optimization_status is not None:
        return optimization_status
    if named_invalid is not None:
        updates, expected, local_sites, mutate_defs = named_invalid
        return expect_invalid(rootdir, case_name, updates, expected, mpi_procs, local_sites, mutate_defs)

    bf_workdir = prepare_case(rootdir, case_name, True)
    no_bf_workdir = prepare_case(rootdir, case_name + "_nobf", False)
    if case_name in momentum_projection_cases:
        for workdir in (bf_workdir, no_bf_workdir):
            update_modpara(workdir, {"NMPTrans": "2"})
            make_momentum_projection(workdir)
    init_path = write_nonidentity_init(bf_workdir) if nonidentity_momentum_case else None

    bf_proc = run_vmc(rootdir, bf_workdir, mpi_procs, init_path)
    if bf_proc.returncode != 0:
        print(bf_proc.stdout)
        return bf_proc.returncode
    if nonidentity_momentum_case:
        for filename, label in (
            ("zvo_out_001.dat", "zvo_out"),
            ("zvo_cisajs_001.dat", "OneBodyG"),
            ("zvo_cisajscktalt_001.dat", "TwoBodyG"),
        ):
            status = assert_finite_nonzero_rows(os.path.join(bf_workdir, "output", filename), label)
            if status != 0:
                return status
        return 0

    no_bf_proc = run_vmc(rootdir, no_bf_workdir, mpi_procs)
    if no_bf_proc.returncode != 0:
        print(no_bf_proc.stdout)
        return no_bf_proc.returncode

    bf_row = read_first_row(os.path.join(bf_workdir, "output", "zvo_out_001.dat"))
    no_bf_row = read_first_row(os.path.join(no_bf_workdir, "output", "zvo_out_001.dat"))
    if len(bf_row) != len(no_bf_row):
        print("ERROR: zvo_out column mismatch: bf={} no_bf={}".format(len(bf_row), len(no_bf_row)))
        return -1

    max_diff = max(abs(x - y) for x, y in zip(bf_row, no_bf_row))
    if max_diff > 1.0e-10:
        print("ERROR: BackFlow FSZ identity energy mismatch: max_abs_diff={:.3e}".format(max_diff))
        print("bf    {}".format(bf_row))
        print("no-bf {}".format(no_bf_row))
        return -1

    comparisons = [
        ("zvo_cisajs_001.dat", "OneBodyG"),
        ("zvo_cisajscktalt_001.dat", "TwoBodyG"),
    ]
    for filename, label in comparisons:
        bf_rows = read_float_rows(os.path.join(bf_workdir, "output", filename))
        no_bf_rows = read_float_rows(os.path.join(no_bf_workdir, "output", filename))
        diff = max_abs_diff(bf_rows, no_bf_rows)
        if diff > 1.0e-10:
            print("ERROR: BackFlow FSZ identity {} mismatch: max_abs_diff={:.3e}".format(label, diff))
            return -1

    invalid_cases = [
        (
            case_name + "_InvalidLocSpin",
            {"NExUpdatePath": "1"},
            "BackFlow MVP does not support NLocalSpin > 0",
            [0],
        ),
    ]
    for name, updates, expected, local_sites in invalid_cases:
        status = expect_invalid(rootdir, name, updates, expected, mpi_procs, local_sites)
        if status != 0:
            return status

    return 0


if __name__ == "__main__":
    sys.exit(main())
