from __future__ import print_function

import math
import os
import shutil
import subprocess
import sys

from backflow_def_helper import build_chain_nn_backflow, write_chain_nn_backflow


def copy_base_defs(refdir, workdir):
    for fn in ("modpara.def", "locspn.def", "trans.def", "qptransidx.def"):
        shutil.copy(os.path.join(refdir, fn), os.path.join(workdir, fn))


def write_namelist(workdir, include_backflow):
    lines = [
        "         ModPara  modpara.def",
        "         LocSpin  locspn.def",
        "           Trans  trans.def",
        "        OneBodyG  greenone.def",
        "        TwoBodyG  greentwo.def",
        " OrbitalGeneral  orbitalidxgen.def",
        "        TransSym  qptransidx.def",
    ]
    if include_backflow:
        lines.extend([
            "              BF  bf.def",
            "         BFRange  rangebf.def",
        ])
    with open(os.path.join(workdir, "namelist.def"), "w") as fp:
        fp.write("\n".join(lines) + "\n")


def write_orbital_general(workdir, nsite, complex_type=1, optimize=True):
    nsite2 = 2 * nsite
    norbital = nsite2 * (nsite2 - 1) // 2
    opt_flag = 1 if optimize else 0
    lines = [
        "=============================================",
        "NOrbitalIdx         {}".format(norbital),
        "ComplexType          {}".format(complex_type),
        "=============================================",
        "=============================================",
    ]
    idx = 0
    for orb_i in range(nsite2):
        for orb_j in range(orb_i + 1, nsite2):
            lines.append(
                "{:5d} {:2d} {:6d} {:2d} {:6d}      1".format(
                    orb_i % nsite, orb_i // nsite,
                    orb_j % nsite, orb_j // nsite,
                    idx,
                )
            )
            idx += 1
    for idx in range(norbital):
        lines.append("{:5d}      {}".format(idx, opt_flag))
    with open(os.path.join(workdir, "orbitalidxgen.def"), "w") as fp:
        fp.write("\n".join(lines) + "\n")


def write_green_defs(workdir):
    one_body_rows = [
        (0, 0, 0, 0),
        (0, 0, 1, 0),
        (0, 1, 0, 1),
        (0, 1, 1, 1),
    ]
    with open(os.path.join(workdir, "greenone.def"), "w") as fp:
        fp.write("===============================\n")
        fp.write("NCisAjs         {}\n".format(len(one_body_rows)))
        fp.write("===============================\n")
        fp.write("======== Green functions ======\n")
        fp.write("===============================\n")
        for row in one_body_rows:
            fp.write(" ".join("{:5d}".format(value) for value in row) + "\n")

    two_body_rows = [
        (0, 0, 0, 0, 0, 1, 0, 1),
        (0, 0, 1, 0, 2, 1, 3, 1),
        (0, 1, 1, 1, 2, 0, 3, 0),
    ]
    with open(os.path.join(workdir, "greentwo.def"), "w") as fp:
        fp.write("=============================================\n")
        fp.write("NCisAjsCktAltDC         {}\n".format(len(two_body_rows)))
        fp.write("=============================================\n")
        fp.write("======== Green functions for BF-FSZ ========\n")
        fp.write("=============================================\n")
        for row in two_body_rows:
            fp.write(" ".join("{:5d}".format(value) for value in row) + "\n")


def build_stale_base_two_body_rows(nsite=4):
    general_rows = []
    contracted_rows = []

    # Cover every spin-conserving double hop so at least one general-path term
    # is active for every half-filled sample generated by this fixture.
    for s, t in ((0, 1), (1, 0)):
        for rj in range(nsite):
            for ri in range(nsite):
                if ri == rj:
                    continue
                for rl in range(nsite):
                    for rk in range(nsite):
                        if rk == rl:
                            continue
                        general_rows.append((ri, s, rj, s, rk, t, rl, t))

        # rk == rl dispatches to GreenFunc1BF_fsz after checking the density.
        # Listing all sites and hops guarantees an active contracted term after
        # the last active general term has overwritten global SlaterElmBF.
        for rk in range(nsite):
            for rj in range(nsite):
                for ri in range(nsite):
                    if ri != rj:
                        contracted_rows.append((ri, s, rj, s, rk, t, rk, t))

    return general_rows, contracted_rows


def write_two_body_rows(workdir, rows):
    with open(os.path.join(workdir, "greentwo.def"), "w") as fp:
        fp.write("=============================================\n")
        fp.write("NCisAjsCktAltDC         {}\n".format(len(rows)))
        fp.write("=============================================\n")
        fp.write("======== Green functions for BF-FSZ ========\n")
        fp.write("=============================================\n")
        for row in rows:
            fp.write(" ".join("{:5d}".format(value) for value in row) + "\n")


def replace_data_line(workdir, filename, row):
    path = os.path.join(workdir, filename)
    with open(path) as fp:
        lines = fp.readlines()
    if len(lines) < 6:
        raise RuntimeError("{} has no data row".format(filename))
    lines[5] = row
    with open(path, "w") as fp:
        fp.writelines(lines)


def make_spin_changing_transfer(workdir):
    replace_data_line(
        workdir,
        "trans.def",
        "    1     0     0     1         1.000000000000000         0.000000000000000\n",
    )


def make_spin_changing_one_body_g(workdir):
    replace_data_line(
        workdir,
        "greenone.def",
        "    0     0     1     1\n",
    )


def write_spin_changing_c1_defs(workdir):
    transfer_rows = [
        (0, 0, 0, 1, 0.70, 0.0),
        (0, 1, 0, 0, 0.70, 0.0),
        (1, 0, 0, 1, -0.40, 0.0),
        (0, 1, 1, 0, -0.40, 0.0),
    ]
    with open(os.path.join(workdir, "trans.def"), "w") as fp:
        fp.write("========================\n")
        fp.write("NTransfer      {}\n".format(len(transfer_rows)))
        fp.write("========================\n")
        fp.write("========i_j_s_tijs=======\n")
        fp.write("========================\n")
        for ri, s, rj, t, real, imag in transfer_rows:
            fp.write(
                "{:5d} {:5d} {:5d} {:5d} {:25.15f} {:25.15f}\n".format(
                    ri, s, rj, t, real, imag,
                )
            )

    one_body_rows = [
        (0, 0, 0, 0),
        (0, 0, 0, 1),
        (0, 1, 0, 0),
        (1, 0, 0, 1),
        (0, 1, 1, 0),
        (0, 0, 1, 0),
    ]
    with open(os.path.join(workdir, "greenone.def"), "w") as fp:
        fp.write("===============================\n")
        fp.write("NCisAjs         {}\n".format(len(one_body_rows)))
        fp.write("===============================\n")
        fp.write("======== Green functions ======\n")
        fp.write("===============================\n")
        for row in one_body_rows:
            fp.write(" ".join("{:5d}".format(value) for value in row) + "\n")


def spin_orbital_row(indices, nsite=4):
    row = []
    for index in indices:
        row.extend((index % nsite, index // nsite))
    return tuple(row)


def build_spin_changing_c2_rows():
    a, b, c, d = 0, 5, 2, 7
    classes = [
        (a, a, a, a),
        (a, a, a, b),
        (a, a, b, a),
        (a, a, b, b),
        (a, a, b, c),
        (a, b, a, b),
        (a, b, a, a),
        (a, b, a, c),
        (a, b, b, a),
        (a, b, c, a),
        (a, b, b, b),
        (a, b, b, c),
        (a, b, c, b),
        (a, b, c, c),
        (a, b, c, d),
    ]
    return [spin_orbital_row(indices) for indices in classes]


def write_c2_detail_profile_defs(workdir):
    write_spin_changing_c2_defs(workdir)
    class_rows = build_spin_changing_c2_rows()
    weighted_rows = []
    for class_id, row in enumerate(class_rows, 1):
        weighted_rows.extend([row] * class_id)
    write_two_body_rows(workdir, weighted_rows)


def append_namelist_entry(workdir, keyword, filename):
    path = os.path.join(workdir, "namelist.def")
    with open(path) as fp:
        lines = fp.readlines()
    if not any(line.split() and line.split()[0] == keyword for line in lines):
        lines.append("{:>16}  {}\n".format(keyword, filename))
    with open(path, "w") as fp:
        fp.writelines(lines)


def write_spin_changing_c2_defs(workdir, reverse_two_body=False):
    write_spin_changing_c1_defs(workdir)
    two_body_rows = build_spin_changing_c2_rows()
    if reverse_two_body:
        two_body_rows = list(reversed(two_body_rows))
    write_two_body_rows(workdir, two_body_rows)

    with open(os.path.join(workdir, "pairhop.def"), "w") as fp:
        fp.write("=============================================\n")
        fp.write("NPairHopp          1\n")
        fp.write("=============================================\n")
        fp.write("====== Pair-Hopping term ====================\n")
        fp.write("=============================================\n")
        fp.write("    0     1          0.370000000000000\n")

    with open(os.path.join(workdir, "exchange.def"), "w") as fp:
        fp.write("=============================================\n")
        fp.write("NExchange          1\n")
        fp.write("=============================================\n")
        fp.write("====== ExchangeCoupling coupling ============\n")
        fp.write("=============================================\n")
        fp.write("    1     2         -0.230000000000000\n")

    interall_rows = [
        (0, 0, 1, 1, 2, 0, 3, 1, 0.31, 0.0),
        (3, 1, 2, 0, 1, 1, 0, 0, 0.31, 0.0),
        (0, 0, 0, 1, 1, 1, 1, 0, -0.19, 0.0),
    ]
    with open(os.path.join(workdir, "interall.def"), "w") as fp:
        fp.write("=============================================\n")
        fp.write("NInterAll          {}\n".format(len(interall_rows)))
        fp.write("=============================================\n")
        fp.write("====== General two-body interactions ========\n")
        fp.write("=============================================\n")
        for row in interall_rows:
            fp.write(" ".join("{}".format(value) for value in row) + "\n")

    append_namelist_entry(workdir, "PairHop", "pairhop.def")
    append_namelist_entry(workdir, "Exchange", "exchange.def")
    append_namelist_entry(workdir, "InterAll", "interall.def")
    make_spin_changing_two_body_g_ex(workdir)
    return two_body_rows


def make_spin_changing_two_body_g(workdir):
    replace_data_line(
        workdir,
        "greentwo.def",
        "    0     0     0     1     0     1     0     1\n",
    )


def make_spin_changing_two_body_g_ex(workdir):
    rows = [
        (0, 0, 1, 1, 2, 0, 3, 0),
    ]
    with open(os.path.join(workdir, "greentwoex.def"), "w") as fp:
        fp.write("=============================================\n")
        fp.write("NCisAjsCktAlt         {}\n".format(len(rows)))
        fp.write("=============================================\n")
        fp.write("======== Green functions for BF-FSZ ========\n")
        fp.write("=============================================\n")
        for row in rows:
            fp.write(" ".join("{:5d}".format(value) for value in row) + "\n")

    namelist_path = os.path.join(workdir, "namelist.def")
    with open(namelist_path) as fp:
        lines = fp.readlines()
    if not any(line.split() and line.split()[0] == "TwoBodyGEx" for line in lines):
        lines.append("      TwoBodyGEx  greentwoex.def\n")
    with open(namelist_path, "w") as fp:
        fp.writelines(lines)


def make_momentum_projection(workdir):
    with open(os.path.join(workdir, "qptransidx.def"), "w") as fp:
        fp.write("=============================================\n")
        fp.write("NQPTrans          2\n")
        fp.write("=============================================\n")
        fp.write("======== TrIdx_TrWeight_and_TrIdx_i_xi ======\n")
        fp.write("=============================================\n")
        fp.write("0    1.00000    0.00000\n")
        fp.write("1    1.00000    0.00000\n")
        fp.write("    0      0      0      1\n")
        fp.write("    0      1      1      1\n")
        fp.write("    0      2      2      1\n")
        fp.write("    0      3      3      1\n")
        fp.write("    1      0      1      1\n")
        fp.write("    1      1      2      1\n")
        fp.write("    1      2      3      1\n")
        fp.write("    1      3      0      1\n")


def write_locspn(workdir, local_sites, nsite=4):
    local_sites = set(local_sites)
    with open(os.path.join(workdir, "locspn.def"), "w") as fp:
        fp.write("================================\n")
        fp.write("NlocalSpin     {}\n".format(len(local_sites)))
        fp.write("================================\n")
        fp.write("========i_1LocSpn_0IteElc ======\n")
        fp.write("================================\n")
        for site in range(nsite):
            fp.write("{:5d} {:6d}\n".format(site, 1 if site in local_sites else 0))


def update_modpara(workdir, updates):
    path = os.path.join(workdir, "modpara.def")
    found = set()
    lines = []
    with open(path) as fp:
        for line in fp:
            cols = line.split()
            if cols and cols[0] in updates:
                lines.append("{:<15} {}\n".format(cols[0], updates[cols[0]]))
                found.add(cols[0])
            else:
                lines.append(line)
    for key, value in updates.items():
        if key not in found:
            lines.append("{:<15} {}\n".format(key, value))
    with open(path, "w") as fp:
        fp.writelines(lines)


def parse_norbitalidx(path):
    with open(path) as fp:
        for line in fp:
            cols = line.split()
            if len(cols) >= 2 and cols[0] == "NOrbitalIdx":
                return int(cols[1])
    raise RuntimeError("NOrbitalIdx was not found in {}".format(path))


def write_nonidentity_init_parameter(path, nprojbf, nslater):
    projbf_values = [
        0.93, 0.08, -0.05, 0.035, -0.025,
        0.015, -0.012, 0.010, -0.007, 0.005,
    ]
    if nprojbf < 2:
        raise RuntimeError("non-identity BackFlow test requires at least two ProjBF parameters")

    values = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    for idx in range(nprojbf):
        real = projbf_values[idx] if idx < len(projbf_values) else 0.001 / float(idx + 1)
        values.extend([real, 0.0, 0.0])
    matrix_width = int(round(math.sqrt(nslater)))
    for idx in range(nslater):
        if matrix_width * matrix_width == nslater:
            row = idx // matrix_width
            col = idx % matrix_width
            real = 1.0 + 0.1 * row if row == col else 0.03 * float(row - col)
        else:
            real = math.sin(0.37 * (idx + 1))
        values.extend([real, 0.0, 0.0])

    with open(path, "w") as fp:
        fp.write(" ".join("{:.18e}".format(value) for value in values))
        fp.write("\n")


def write_nonidentity_init(workdir, nsite=4):
    definition = build_chain_nn_backflow(length=nsite, optimize=False)
    nslater = parse_norbitalidx(os.path.join(workdir, "orbitalidxgen.def"))
    init_name = "nonidentity_init.dat"
    write_nonidentity_init_parameter(
        os.path.join(workdir, init_name),
        definition.n_proj_bf,
        nslater,
    )
    return init_name


def run_vmc(rootdir, workdir, mpi_procs=None, init_path=None, extra_env=None):
    bin_to_test = os.path.join(rootdir, "..", "..", "src", "mVMC", "vmc.out")
    cmd = [bin_to_test, "-e", "namelist.def"]
    if init_path is not None:
        cmd.append(init_path)
    if mpi_procs:
        mpi_args = os.environ.get("MVMC_MPI_ARGS", "").split()
        cmd = ["mpirun"] + mpi_args + ["-np", mpi_procs] + cmd
    env = os.environ.copy()
    if extra_env is not None:
        env.update(extra_env)
    proc = subprocess.run(
        cmd,
        cwd=workdir,
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    with open(os.path.join(workdir, "vmc.log"), "w") as fp:
        fp.write(proc.stdout)
    return proc


def read_first_row(path):
    with open(path) as fp:
        for line in fp:
            cols = line.split()
            if cols:
                return [float(x) for x in cols]
    raise RuntimeError("no numeric row in {}".format(path))


def read_float_rows(path):
    rows = []
    with open(path) as fp:
        for line in fp:
            cols = line.split()
            if cols:
                rows.append([float(x) for x in cols])
    return rows


def read_flat_floats(path):
    values = []
    with open(path) as fp:
        for line in fp:
            values.extend(float(x) for x in line.split())
    return values


def read_sampling_counters(path):
    last = None
    with open(path) as fp:
        for line in fp:
            cols = line.replace(":", " ").split()
            if len(cols) < 7 or not cols[0].isdigit() or cols[0] == "00000":
                continue
            last = {
                "acc_hop": float(cols[1]),
                "acc_lsf": float(cols[3]),
                "n_hop": int(cols[4]),
                "n_lsf": int(cols[6]),
            }
    if last is None:
        raise RuntimeError("sampling counters were not found in {}".format(path))
    return last


def read_child_opt_rows(path):
    rows = []
    with open(path) as fp:
        for line in fp:
            cols = line.split()
            if len(cols) < 3:
                continue
            try:
                idx = int(cols[0])
                real = float(cols[1])
                imag = float(cols[2])
            except ValueError:
                continue
            rows.append((idx, real, imag))
    return rows


def read_key_values(path):
    values = {}
    with open(path) as fp:
        for line in fp:
            cols = line.split()
            if len(cols) >= 2:
                values[cols[0]] = cols[1:]
    return values


def read_bffsz_profile_stats(path, source, kind):
    marker = "BF-FSZ {} {} stats".format(source, kind)
    with open(path) as fp:
        for line in fp:
            if marker not in line:
                continue
            fields = {}
            for token in line.split():
                if "=" in token:
                    key, value = token.split("=", 1)
                    fields[key] = value
            if not all(key in fields for key in ("calls", "mean", "max")):
                break
            return int(fields["calls"]), float(fields["mean"]), int(fields["max"])
    raise RuntimeError("{} was not found in {}".format(marker, path))


def read_bffsz_profile_hist_sum(path, source, kind):
    marker = "BF-FSZ {} {}".format(source, kind)
    with open(path) as fp:
        for line in fp:
            if marker not in line:
                continue
            values = []
            for token in line.split():
                if ":" not in token:
                    continue
                try:
                    values.append(int(token.rsplit(":", 1)[1]))
                except ValueError:
                    pass
            if values:
                return sum(values)
    raise RuntimeError("{} was not found in {}".format(marker, path))


def read_bffsz_pf_paths(path, source):
    marker = "BF-FSZ {} Pfaffian paths".format(source)
    with open(path) as fp:
        for line in fp:
            if marker not in line:
                continue
            values = {}
            for token in line.split():
                if ":" not in token:
                    continue
                key, value = token.rsplit(":", 1)
                try:
                    values[key] = int(value)
                except ValueError:
                    pass
            if all(key in values for key in ("optimized", "direct-full", "fallback")):
                return values
    raise RuntimeError("{} was not found in {}".format(marker, path))

def read_bffsz_inv_paths(path):
    marker = "BF-FSZ accepted inverse paths"
    with open(path) as fp:
        for line in fp:
            if marker not in line:
                continue
            values = {}
            for token in line.split():
                if ":" not in token:
                    continue
                key, value = token.rsplit(":", 1)
                try:
                    values[key] = int(value)
                except ValueError:
                    pass
            if all(key in values for key in ("optimized", "direct-full", "fallback")):
                return values
    raise RuntimeError("{} was not found in {}".format(marker, path))


def read_bffsz_green_materialize(path):
    marker = "BF-FSZ green full materialize"
    with open(path) as fp:
        for line in fp:
            if marker not in line:
                continue
            values = {}
            for token in line.split():
                if ":" not in token:
                    continue
                key, value = token.rsplit(":", 1)
                try:
                    values[key] = int(value)
                except ValueError:
                    pass
            if all(key in values for key in ("direct-full", "fallback", "oracle")):
                return values
    raise RuntimeError("{} was not found in {}".format(marker, path))


def read_bffsz_sample_materialize(path):
    marker = "BF-FSZ sample full materialize"
    with open(path) as fp:
        for line in fp:
            if marker not in line:
                continue
            values = {}
            for token in line.split():
                if ":" not in token:
                    continue
                key, value = token.rsplit(":", 1)
                try:
                    values[key] = int(value)
                except ValueError:
                    pass
            required = ("direct-full", "pf-fallback", "inv-fallback", "oracle")
            if all(key in values for key in required):
                return values
    raise RuntimeError("{} was not found in {}".format(marker, path))


def read_bffsz_sample_commits(path):
    marker = "BF-FSZ sample Slater commits"
    with open(path) as fp:
        for line in fp:
            if marker not in line:
                continue
            values = {}
            for token in line.split():
                if ":" not in token:
                    continue
                key, value = token.rsplit(":", 1)
                try:
                    values[key] = int(value)
                except ValueError:
                    pass
            if all(key in values for key in ("optimized", "direct-full", "fallback")):
                return values
    raise RuntimeError("{} was not found in {}".format(marker, path))


def read_bffsz_inv_detail(path):
    components = {}
    total = None
    component_marker = "BF-FSZ inverse detail component="
    total_marker = "BF-FSZ inverse detail total "
    with open(path) as fp:
        for line in fp:
            if component_marker in line:
                fields = {}
                for token in line.split():
                    if "=" in token:
                        key, value = token.split("=", 1)
                        fields[key] = value
                required = (
                    "component",
                    "seconds_rank0",
                    "seconds_max_rank",
                    "share_rank0",
                )
                if all(key in fields for key in required):
                    components[fields["component"]] = {
                        "seconds_rank0": float(fields["seconds_rank0"]),
                        "seconds_max_rank": float(fields["seconds_max_rank"]),
                        "share_rank0": float(fields["share_rank0"]),
                    }
            elif total_marker in line:
                fields = {}
                for token in line.split():
                    if "=" in token:
                        key, value = token.split("=", 1)
                        fields[key] = value
                required = (
                    "timer63_seconds_rank0",
                    "classified_seconds_rank0",
                    "unclassified_seconds_rank0",
                )
                if all(key in fields for key in required):
                    total = {key: float(fields[key]) for key in required}
    if not components or total is None:
        raise RuntimeError("BF-FSZ inverse detail profile was not found in {}".format(path))
    return components, total


def has_bffsz_inv_detail(path):
    marker = "BF-FSZ inverse detail profile"
    with open(path) as fp:
        return any(marker in line for line in fp)


def read_bffsz_inv_gemm_check(path):
    marker = "BF-FSZ inverse GEMM checks"
    with open(path) as fp:
        for line in fp:
            if marker in line:
                fields = {}
                for token in line.split():
                    if "=" in token:
                        key, value = token.split("=", 1)
                        fields[key] = value
                if "calls" in fields and "scaled_max" in fields:
                    return int(fields["calls"]), float(fields["scaled_max"])
    raise RuntimeError("{} was not found in {}".format(marker, path))


def get_float(values, key):
    if key not in values:
        raise RuntimeError("{} was not found in dump".format(key))
    return float(values[key][0])


def get_int(values, key):
    if key not in values:
        raise RuntimeError("{} was not found in dump".format(key))
    return int(values[key][0])


def assert_finite_nonzero_rows(path, label):
    rows = read_float_rows(path)
    if not rows:
        print("ERROR: {} output is empty.".format(label))
        return -1
    max_abs = 0.0
    for row in rows:
        for value in row:
            if not math.isfinite(value):
                print("ERROR: {} output contains non-finite values.".format(label))
                return -1
            max_abs = max(max_abs, abs(value))
    if max_abs <= 1.0e-12:
        print("ERROR: {} output is vacuous: all values are zero.".format(label))
        return -1
    return 0


def assert_finite_values(values, label):
    if not values:
        print("ERROR: {} is empty.".format(label))
        return -1
    for value in values:
        if not math.isfinite(value):
            print("ERROR: {} contains non-finite values.".format(label))
            return -1
    return 0


def assert_child_opt_file(workdir, filename, expected_rows, zqp_group_offset, label):
    child_path = os.path.join(workdir, "output", filename)
    if not os.path.exists(child_path):
        print("ERROR: {} was not created.".format(filename))
        return -1
    rows = read_child_opt_rows(child_path)
    if len(rows) != expected_rows:
        print("ERROR: {} row count mismatch: got {}, expected {}".format(
            filename, len(rows), expected_rows))
        return -1
    zqp_path = os.path.join(workdir, "output", "zqp_opt.dat")
    zqp_values = read_flat_floats(zqp_path)
    for local_idx, real, imag in rows:
        if local_idx < 0 or local_idx >= expected_rows:
            print("ERROR: {} has invalid local index {}".format(filename, local_idx))
            return -1
        if not (math.isfinite(real) and math.isfinite(imag)):
            print("ERROR: {} contains non-finite values.".format(filename))
            return -1
        group = zqp_group_offset + local_idx
        zqp_pos = 3 * group
        if zqp_pos + 1 >= len(zqp_values):
            print("ERROR: zqp_opt.dat is too short for {} group {}".format(label, group))
            return -1
        if max(abs(real - zqp_values[zqp_pos]), abs(imag - zqp_values[zqp_pos + 1])) > 1.0e-12:
            print("ERROR: {} does not match zqp_opt.dat at row {}".format(filename, local_idx))
            return -1
    return 0


def read_orbital_opt_rows(workdir):
    return read_child_opt_rows(os.path.join(workdir, "output", "zqp_orbital_general_opt.dat"))


def compare_child_rows(left, right, tolerance, label):
    if len(left) != len(right):
        print("ERROR: {} row count mismatch: left={} right={}".format(label, len(left), len(right)))
        return -1
    max_diff = 0.0
    for (li, lr, lii), (ri, rr, rii) in zip(left, right):
        if li != ri:
            print("ERROR: {} local index mismatch: left={} right={}".format(label, li, ri))
            return -1
        max_diff = max(max_diff, abs(lr - rr), abs(lii - rii))
    if max_diff > tolerance:
        print("ERROR: {} mismatch: max_abs_diff={:.3e}".format(label, max_diff))
        return -1
    return 0


def max_abs_diff(left_rows, right_rows):
    if len(left_rows) != len(right_rows):
        raise RuntimeError("row count mismatch: left={} right={}".format(len(left_rows), len(right_rows)))
    max_diff = 0.0
    for left, right in zip(left_rows, right_rows):
        if len(left) != len(right):
            raise RuntimeError("column count mismatch: left={} right={}".format(len(left), len(right)))
        for x, y in zip(left, right):
            max_diff = max(max_diff, abs(x-y))
    return max_diff


def prepare_case(rootdir, name, include_backflow, orbital_complex_type=1,
                 orbital_optimize=True, backflow_optimize=False):
    refdir = os.path.join(rootdir, "data", "BackFlow_Identity_Complex")
    workdir = os.path.join(rootdir, "work", name)
    if os.path.exists(workdir):
        shutil.rmtree(workdir)
    os.makedirs(workdir)

    copy_base_defs(refdir, workdir)
    write_namelist(workdir, include_backflow)
    write_orbital_general(
        workdir,
        nsite=4,
        complex_type=orbital_complex_type,
        optimize=orbital_optimize,
    )
    write_green_defs(workdir)
    if include_backflow:
        write_chain_nn_backflow(workdir, length=4, optimize=backflow_optimize)
    return workdir


def run_twobody_stale_base_case(rootdir, case_name, mpi_procs=None):
    pf_update_cases = {
        "BackFlow_FSZ_PfUpdate_NonIdentity_Complex": "optimized",
        "BackFlow_FSZ_PfUpdate_NonIdentity_Complex_mpi": "optimized",
        "BackFlow_FSZ_PfUpdate_MoreRanks_NonIdentity_Complex_mpi": "optimized",
        "BackFlow_FSZ_PfUpdate_Fallback_NonIdentity_Complex": "fallback",
        "BackFlow_FSZ_PfUpdate_ExactZeroFallback_NonIdentity_Complex": "exact-zero",
        "BackFlow_FSZ_PfUpdate_LapackFallback_NonIdentity_Complex": "lapack",
        "BackFlow_FSZ_PfUpdate_RankFallback_NonIdentity_Complex_mpi": "rank-fallback",
        "BackFlow_FSZ_PfUpdate_DirectFull_NonIdentity_Complex": "direct-full",
        "BackFlow_FSZ_PfUpdate_PermutedLabels_NonIdentity_Complex": "permuted",
        "BackFlow_FSZ_PfUpdate_ExplicitState_NonIdentity_Complex": "explicit-state",
        "BackFlow_FSZ_PfUpdate_InvalidArguments_NonIdentity_Complex": "arguments",
    }
    inv_update_cases = {
        "BackFlow_FSZ_InvUpdate_NonIdentity_Complex": "optimized",
        "BackFlow_FSZ_InvUpdate_NonIdentity_Complex_mpi": "optimized",
        "BackFlow_FSZ_InvDetailProfile_NonIdentity_Complex": "detail",
        "BackFlow_FSZ_InvDetailProfile_NonIdentity_Complex_mpi": "detail",
        "BackFlow_FSZ_InvResidualGemm_NonIdentity_Complex": "gemm",
        "BackFlow_FSZ_InvResidualGemm_NonIdentity_Complex_mpi": "gemm",
        "BackFlow_FSZ_InvWoodburyGemm_NonIdentity_Complex": "gemm",
        "BackFlow_FSZ_InvWoodburyGemm_NonIdentity_Complex_mpi": "gemm",
        "BackFlow_FSZ_InvScanFusion_NonIdentity_Complex": "gemm",
        "BackFlow_FSZ_InvScanFusion_NonIdentity_Complex_mpi": "gemm",
        "BackFlow_FSZ_InvUpdate_MoreRanks_NonIdentity_Complex_mpi": "optimized",
        "BackFlow_FSZ_InvUpdate_Fallback_NonIdentity_Complex": "fallback",
        "BackFlow_FSZ_InvUpdate_GetrfFallback_NonIdentity_Complex": "getrf",
        "BackFlow_FSZ_InvUpdate_GetriFallback_NonIdentity_Complex": "getri",
        "BackFlow_FSZ_InvUpdate_RankFallback_NonIdentity_Complex_mpi": "rank-fallback",
        "BackFlow_FSZ_InvUpdate_DirectFull_NonIdentity_Complex": "direct-full",
        "BackFlow_FSZ_InvUpdate_ExplicitState_NonIdentity_Complex": "explicit-state",
        "BackFlow_FSZ_InvUpdate_InvalidArguments_NonIdentity_Complex": "arguments",
    }
    matrix_free_cases = {
        "BackFlow_FSZ_MatrixFreeRows_NonIdentity_Complex": "optimized",
        "BackFlow_FSZ_MatrixFreeRows_NonIdentity_Complex_mpi": "optimized",
        "BackFlow_FSZ_MatrixFreeRows_NonIdentity_Complex_omp": "optimized",
        "BackFlow_FSZ_MatrixFreeRows_InvalidArguments_NonIdentity_Complex": "arguments",
    }
    green_matrix_free_cases = {
        "BackFlow_FSZ_GreenMatrixFree_Lazy_NonIdentity_Complex": "lazy",
        "BackFlow_FSZ_GreenMatrixFree_Lazy_NonIdentity_Complex_mpi": "lazy",
        "BackFlow_FSZ_GreenMatrixFree_Lazy_NonIdentity_Complex_omp": "lazy",
    }
    sampling_matrix_free_cases = {
        "BackFlow_FSZ_SamplingMatrixFree_Lazy_NonIdentity_Complex": "lazy",
        "BackFlow_FSZ_SamplingMatrixFree_Lazy_NonIdentity_Complex_mpi": "lazy",
        "BackFlow_FSZ_SamplingMatrixFree_Lazy_NonIdentity_Complex_omp": "lazy",
        "BackFlow_FSZ_SamplingMatrixFree_Reject_NonIdentity_Complex": "reject",
        "BackFlow_FSZ_SamplingMatrixFree_Reject_NonIdentity_Complex_mpi": "reject",
    }
    affected_cases = (
        "BackFlow_FSZ_AffectedRows_NonIdentity_Complex",
        "BackFlow_FSZ_AffectedRows_NonIdentity_Complex_mpi",
    ) + tuple(pf_update_cases) + tuple(inv_update_cases) \
        + tuple(matrix_free_cases) + tuple(green_matrix_free_cases) \
        + tuple(sampling_matrix_free_cases)
    if case_name != "BackFlow_FSZ_TwoBodyG_StaleBase_NonIdentity_Complex" \
            and case_name not in affected_cases:
        return None

    general_rows, contracted_rows = build_stale_base_two_body_rows()
    ordered_rows = general_rows + contracted_rows
    reference_rows = contracted_rows + general_rows
    reference_case_rows = reference_rows
    if case_name in pf_update_cases and pf_update_cases[case_name] == "permuted":
        reference_case_rows = ordered_rows
    if case_name in inv_update_cases and inv_update_cases[case_name] == "detail":
        reference_case_rows = ordered_rows

    ordered_workdir = prepare_case(rootdir, case_name, True)
    reference_workdir = prepare_case(rootdir, case_name + "_reference", True)
    for workdir, rows in (
        (ordered_workdir, ordered_rows),
        (reference_workdir, reference_case_rows),
    ):
        update_modpara(workdir, {"NVMCSample": "1"})
        if (case_name in inv_update_cases or case_name in matrix_free_cases
                or case_name in green_matrix_free_cases
                or case_name in sampling_matrix_free_cases) \
                and mpi_procs:
            update_modpara(workdir, {"NSplitSize": str(mpi_procs)})
        if case_name in affected_cases:
            update_modpara(workdir, {"NMPTrans": "2"})
            make_momentum_projection(workdir)
        write_two_body_rows(workdir, rows)

    ordered_init = write_nonidentity_init(ordered_workdir)
    reference_init = write_nonidentity_init(reference_workdir)
    if case_name in green_matrix_free_cases \
            or case_name in sampling_matrix_free_cases:
        ordered_env = {"MVMC_BF_PROFILE": "1"}
    else:
        ordered_env = {
            "MVMC_BF_FSZ_GREEN_REBUILD_CHECK": "1",
            "MVMC_BF_FSZ_AFFECTED_CHECK": "1",
            "MVMC_BF_FSZ_MATRIX_FREE_CHECK": "1",
            "MVMC_BF_PROFILE": "1",
        }
    if case_name in pf_update_cases:
        ordered_env["MVMC_BF_FSZ_PF_UPDATE_CHECK"] = "1"
        if pf_update_cases[case_name] == "fallback":
            ordered_env["MVMC_BF_FSZ_PF_UPDATE_FORCE_FALLBACK"] = "1"
        elif pf_update_cases[case_name] == "exact-zero":
            ordered_env["MVMC_BF_FSZ_PF_UPDATE_INJECT_STATUS"] = "1"
        elif pf_update_cases[case_name] == "lapack":
            ordered_env["MVMC_BF_FSZ_PF_UPDATE_INJECT_STATUS"] = "2"
        elif pf_update_cases[case_name] == "rank-fallback":
            ordered_env["MVMC_BF_FSZ_PF_UPDATE_INJECT_STATUS"] = "2"
            ordered_env["MVMC_BF_FSZ_PF_UPDATE_INJECT_RANK"] = "1"
        elif pf_update_cases[case_name] == "direct-full":
            ordered_env["MVMC_BF_FSZ_PF_UPDATE_KFULL"] = "1"
        elif pf_update_cases[case_name] == "permuted":
            ordered_env["MVMC_BF_FSZ_PERMUTE_PARTICLE_LABELS"] = "1"
        elif pf_update_cases[case_name] == "explicit-state":
            ordered_env["MVMC_BF_FSZ_PF_UPDATE_EXPLICIT_STATE_CHECK"] = "1"
        elif pf_update_cases[case_name] == "arguments":
            ordered_env["MVMC_BF_FSZ_PF_UPDATE_ARGUMENT_CHECK"] = "1"
    if case_name in inv_update_cases:
        ordered_env["MVMC_BF_FSZ_INV_UPDATE_CHECK"] = "1"
        mode = inv_update_cases[case_name]
        if mode == "fallback":
            ordered_env["MVMC_BF_FSZ_INV_UPDATE_FORCE_FALLBACK"] = "1"
        elif mode == "getrf":
            ordered_env["MVMC_BF_FSZ_INV_UPDATE_INJECT_STAGE"] = "1"
        elif mode == "getri":
            ordered_env["MVMC_BF_FSZ_INV_UPDATE_INJECT_STAGE"] = "2"
        elif mode == "rank-fallback":
            ordered_env["MVMC_BF_FSZ_INV_UPDATE_INJECT_STAGE"] = "1"
            ordered_env["MVMC_BF_FSZ_INV_UPDATE_INJECT_RANK"] = "1"
        elif mode == "direct-full":
            ordered_env["MVMC_BF_FSZ_PF_UPDATE_KFULL"] = "1"
        elif mode == "explicit-state":
            ordered_env["MVMC_BF_FSZ_INV_UPDATE_EXPLICIT_STATE_CHECK"] = "1"
        elif mode == "arguments":
            ordered_env["MVMC_BF_FSZ_INV_UPDATE_ARGUMENT_CHECK"] = "1"
        elif mode == "detail":
            ordered_env["MVMC_BF_FSZ_INV_DETAIL_PROFILE"] = "1"
        elif mode == "gemm":
            ordered_env["MVMC_BF_FSZ_INV_GEMM_CHECK"] = "1"
    if case_name in matrix_free_cases \
            and matrix_free_cases[case_name] == "arguments":
        ordered_env["MVMC_BF_FSZ_MATRIX_FREE_ARGUMENT_CHECK"] = "1"
        ordered_env["MVMC_BF_FSZ_PF_UPDATE_ARGUMENT_CHECK"] = "1"
        ordered_env["MVMC_BF_FSZ_INV_UPDATE_ARGUMENT_CHECK"] = "1"
    if case_name in sampling_matrix_free_cases \
            and sampling_matrix_free_cases[case_name] == "reject":
        ordered_env["MVMC_BF_FSZ_SAMPLING_REJECT_CHECK"] = "1"
    ordered_proc = run_vmc(
        rootdir,
        ordered_workdir,
        mpi_procs=mpi_procs,
        init_path=ordered_init,
        extra_env=ordered_env,
    )
    if ordered_proc.returncode != 0:
        print(ordered_proc.stdout)
        return ordered_proc.returncode

    reference_env = None
    if case_name in pf_update_cases and pf_update_cases[case_name] == "permuted":
        reference_env = {
            "MVMC_BF_FSZ_PERMUTE_PARTICLE_LABELS": "1",
            "MVMC_BF_FSZ_PF_UPDATE_KFULL": "1",
        }
    elif case_name in sampling_matrix_free_cases \
            and sampling_matrix_free_cases[case_name] == "reject":
        reference_env = {"MVMC_BF_FSZ_SAMPLING_REJECT_CHECK": "1"}
    reference_proc = run_vmc(
        rootdir,
        reference_workdir,
        mpi_procs=mpi_procs,
        init_path=reference_init,
        extra_env=reference_env,
    )
    if reference_proc.returncode != 0:
        print(reference_proc.stdout)
        return reference_proc.returncode

    timer_path = os.path.join(ordered_workdir, "output", "zvo_CalcTimer.dat")
    for source in ("sample", "green"):
        changed_calls, changed_mean, changed_max = read_bffsz_profile_stats(
            timer_path, source, "changed")
        affected_calls, affected_mean, affected_max = read_bffsz_profile_stats(
            timer_path, source, "affected")
        if changed_calls <= 0 or affected_calls != changed_calls:
            print("ERROR: BF-FSZ {} affected profile call mismatch".format(source))
            return -1
        if changed_mean <= 0.0 or changed_max <= 0 or changed_max > 8:
            print("ERROR: BF-FSZ {} changed profile is invalid".format(source))
            return -1
        if affected_mean < 1.0 or affected_max < 1 or affected_max > 4:
            print("ERROR: BF-FSZ {} affected profile is invalid".format(source))
            return -1
        for hist_kind in ("changed hist", "affected hist", "affected ratio hist"):
            if read_bffsz_profile_hist_sum(timer_path, source, hist_kind) != changed_calls:
                print("ERROR: BF-FSZ {} {} count mismatch".format(source, hist_kind))
                return -1

        if case_name in pf_update_cases:
            paths = read_bffsz_pf_paths(timer_path, source)
            mode = pf_update_cases[case_name]
            if mode in ("optimized", "permuted", "explicit-state", "arguments"):
                if paths["optimized"] <= 0 or paths["fallback"] != 0:
                    print("ERROR: BF-FSZ {} optimized Pfaffian path was not isolated".format(source))
                    return -1
            elif mode in ("fallback", "exact-zero", "lapack"):
                if paths["fallback"] <= 0 or paths["optimized"] != 0:
                    print("ERROR: BF-FSZ {} fallback Pfaffian path was not isolated".format(source))
                    return -1
            elif mode == "rank-fallback":
                if paths["fallback"] <= 0 or paths["optimized"] <= 0:
                    print("ERROR: BF-FSZ {} rank-specific Pfaffian paths did not diverge".format(source))
                    return -1
            elif mode == "direct-full":
                if paths["direct-full"] <= 0 or paths["optimized"] != 0 \
                        or paths["fallback"] != 0:
                    print("ERROR: BF-FSZ {} direct-full Pfaffian path was not isolated".format(source))
                    return -1
        if source == "green":
            paths = read_bffsz_pf_paths(timer_path, source)
            materialize = read_bffsz_green_materialize(timer_path)
            expected_oracle = 0 if (
                case_name in green_matrix_free_cases
                or case_name in sampling_matrix_free_cases
            ) else paths["optimized"]
            if materialize["direct-full"] != paths["direct-full"] \
                    or materialize["fallback"] != paths["fallback"] \
                    or materialize["oracle"] != expected_oracle:
                print("ERROR: BF-FSZ Green lazy materialization counters "
                      "do not match path decisions")
                return -1
            if case_name in green_matrix_free_cases \
                    and (paths["optimized"] <= 0 or paths["fallback"] != 0):
                print("ERROR: BF-FSZ Green matrix-free optimized path "
                      "was not exercised cleanly")
                return -1

    if case_name in inv_update_cases:
        paths = read_bffsz_inv_paths(timer_path)
        mode = inv_update_cases[case_name]
        if mode in ("optimized", "detail", "gemm", "explicit-state", "arguments"):
            if paths["optimized"] <= 0 or paths["fallback"] != 0:
                print("ERROR: BF-FSZ optimized inverse path was not isolated")
                return -1
        elif mode in ("fallback", "getrf", "getri", "rank-fallback"):
            if paths["fallback"] <= 0 or paths["optimized"] != 0:
                print("ERROR: BF-FSZ inverse fallback path was not isolated")
                return -1
        elif mode == "direct-full":
            if paths["direct-full"] <= 0 or paths["optimized"] != 0 \
                    or paths["fallback"] != 0:
                print("ERROR: BF-FSZ direct-full inverse path was not isolated")
                return -1
        if mode == "detail":
            components, total = read_bffsz_inv_detail(timer_path)
            expected = {
                "w",
                "small-transpose",
                "u",
                "lapack",
                "correction",
                "scan-antisymmetrize",
                "affected-residual",
                "mpi-agreement",
                "commit-copy",
            }
            if set(components) != expected:
                print("ERROR: BF-FSZ inverse detail component set mismatch")
                return -1
            timer63 = total["timer63_seconds_rank0"]
            classified = total["classified_seconds_rank0"]
            unclassified = total["unclassified_seconds_rank0"]
            if not all(math.isfinite(value) for value in (
                    timer63, classified, unclassified)) \
                    or timer63 <= 0.0 or classified <= 0.0:
                print("ERROR: BF-FSZ inverse detail totals are invalid")
                return -1
            component_sum = 0.0
            for name, values in components.items():
                rank0 = values["seconds_rank0"]
                max_rank = values["seconds_max_rank"]
                share = values["share_rank0"]
                if not all(math.isfinite(value) for value in (
                        rank0, max_rank, share)) \
                        or rank0 < 0.0 or max_rank < 0.0 \
                        or max_rank + 1.0e-9 < rank0:
                    print("ERROR: BF-FSZ inverse detail {} values are invalid".format(name))
                    return -1
                expected_share = rank0 / timer63
                if abs(share - expected_share) > 2.0e-7:
                    print("ERROR: BF-FSZ inverse detail {} share mismatch".format(name))
                    return -1
                component_sum += rank0
            tolerance = max(2.0e-6, 2.0e-5 * timer63)
            if abs(component_sum - classified) > tolerance \
                    or abs(timer63 - classified - unclassified) > tolerance \
                    or classified > timer63 + tolerance:
                print("ERROR: BF-FSZ inverse detail accounting mismatch")
                return -1
            kernel_sum = sum(
                components[name]["seconds_rank0"]
                for name in expected
                if name not in ("mpi-agreement", "commit-copy")
            )
            if kernel_sum <= 0.0:
                print("ERROR: BF-FSZ inverse detail profile was vacuous")
                return -1
            reference_timer_path = os.path.join(
                reference_workdir, "output", "zvo_CalcTimer.dat")
            if has_bffsz_inv_detail(reference_timer_path):
                print("ERROR: BF-FSZ inverse detail profile was enabled implicitly")
                return -1
            for filename in (
                "zvo_out_001.dat",
                "zvo_var_001.dat",
                "zvo_cisajs_001.dat",
                "zvo_cisajscktalt_001.dat",
            ):
                ordered_output = os.path.join(
                    ordered_workdir, "output", filename)
                reference_output = os.path.join(
                    reference_workdir, "output", filename)
                with open(ordered_output, "rb") as ordered_fp:
                    ordered_bytes = ordered_fp.read()
                with open(reference_output, "rb") as reference_fp:
                    reference_bytes = reference_fp.read()
                if ordered_bytes != reference_bytes:
                    print("ERROR: BF-FSZ inverse detail profile changed {}".format(
                        filename))
                    return -1
        elif mode == "gemm":
            calls, scaled_max = read_bffsz_inv_gemm_check(timer_path)
            if calls <= 0 or not math.isfinite(scaled_max) \
                    or scaled_max > 1.0e-11:
                print("ERROR: BF-FSZ inverse GEMM canary failed")
                return -1

    if case_name in sampling_matrix_free_cases:
        mode = sampling_matrix_free_cases[case_name]
        pf_paths = read_bffsz_pf_paths(timer_path, "sample")
        inv_paths = read_bffsz_inv_paths(timer_path)
        materialize = read_bffsz_sample_materialize(timer_path)
        commits = read_bffsz_sample_commits(timer_path)
        sample_calls, _, _ = read_bffsz_profile_stats(
            timer_path, "sample", "changed")
        path_names = ("optimized", "direct-full", "fallback")
        if sum(pf_paths[path] for path in path_names) != sample_calls:
            print("ERROR: BF-FSZ sampling Pfaffian path count "
                  "does not match proposal count")
            return -1
        if materialize["direct-full"] != pf_paths["direct-full"] \
                or materialize["pf-fallback"] != pf_paths["fallback"] \
                or materialize["oracle"] != 0:
            print("ERROR: BF-FSZ sampling lazy materialization counters "
                  "do not match Pfaffian path decisions")
            return -1
        if pf_paths["optimized"] <= 0 or pf_paths["fallback"] != 0 \
                or materialize["inv-fallback"] != 0:
            print("ERROR: BF-FSZ sampling matrix-free optimized path "
                  "was not exercised cleanly")
            return -1
        if mode == "lazy":
            if sum(commits[path] for path in path_names) <= 4:
                print("ERROR: BF-FSZ sampling matrix-free accept path did "
                      "not reach the periodic refresh threshold")
                return -1
            for path in path_names:
                if commits[path] != inv_paths[path]:
                    print("ERROR: BF-FSZ sampling Slater commit count "
                          "does not match accepted inverse path")
                    return -1
        elif mode == "reject":
            if sum(inv_paths[path] for path in path_names) != 0 \
                    or sum(commits[path] for path in path_names) != 0:
                print("ERROR: BF-FSZ rejected sampling proposal "
                      "committed matrix state")
                return -1

    if case_name in pf_update_cases and pf_update_cases[case_name] == "permuted":
        return assert_finite_nonzero_rows(
            os.path.join(ordered_workdir, "output", "zvo_cisajs_001.dat"),
            "permuted-label Pfaffian update",
        )

    ordered_path = os.path.join(ordered_workdir, "output", "zvo_cisajscktalt_001.dat")
    reference_path = os.path.join(reference_workdir, "output", "zvo_cisajscktalt_001.dat")
    ordered_values = read_float_rows(ordered_path)
    reference_values = read_float_rows(reference_path)
    if len(ordered_values) != len(ordered_rows) or len(reference_values) != len(reference_rows):
        print("ERROR: stale-base TwoBodyG output row count mismatch")
        return -1

    ordered_by_term = dict(zip(ordered_rows, ordered_values))
    reference_by_term = dict(zip(reference_case_rows, reference_values))
    diff = max_abs_diff(
        [ordered_by_term[row] for row in ordered_rows],
        [reference_by_term[row] for row in ordered_rows],
    )
    if diff > 1.0e-12:
        print("ERROR: BF-FSZ TwoBodyG depends on general/contracted term order: "
              "max_abs_diff={:.3e}".format(diff))
        return -1

    return assert_finite_nonzero_rows(ordered_path, "stale-base TwoBodyG")


def run_sr_diff_case(rootdir, case_name, mpi_procs=None):
    sr_diff_cases = {
        "BackFlow_FSZ_SRDiff_Identity_Complex": (False, False, True, False),
        "BackFlow_FSZ_SRDiff_Identity_Complex_mpi": (False, False, True, False),
        "BackFlow_FSZ_SRDiff_MomentumProjection_Complex": (True, False, True, False),
        "BackFlow_FSZ_SRDiff_NonIdentity_Complex": (False, True, False, False),
        "BackFlow_FSZ_SRDiff_MomentumProjection_NonIdentity_Complex": (
            True, True, False, False,
        ),
        "BackFlow_FSZ_SRDiff_SpinChanging_NonIdentity_Complex": (
            False, True, False, True,
        ),
    }
    if case_name not in sr_diff_cases:
        return None

    use_momentum, use_nonidentity, check_identity, use_spin_changing = sr_diff_cases[case_name]
    workdir = prepare_case(rootdir, case_name, True)
    update_modpara(workdir, {"NVMCSample": "1"})
    if use_spin_changing:
        update_modpara(workdir, {"2Sz": "-1"})
        write_spin_changing_c2_defs(workdir)
    if use_momentum:
        update_modpara(workdir, {"NMPTrans": "2"})
        make_momentum_projection(workdir)
    init_path = write_nonidentity_init(workdir) if use_nonidentity else None
    dump_path = os.path.join(workdir, "bf_fsz_sr_diff.dat")
    proc = run_vmc(
        rootdir,
        workdir,
        mpi_procs=mpi_procs,
        init_path=init_path,
        extra_env={"MVMC_BF_FSZ_SR_DIFF_DUMP": dump_path},
    )
    if proc.returncode != 0:
        print(proc.stdout)
        return proc.returncode
    if not os.path.exists(dump_path):
        print("ERROR: BF-FSZ SR diff dump was not created")
        return -1

    values = read_key_values(dump_path)
    if get_int(values, "info_bf") != 0:
        print("ERROR: BF-FSZ SR diff base calculation failed")
        return -1
    if get_int(values, "fd_fail_count") != 0:
        print("ERROR: BF-FSZ SR diff finite differences failed")
        print(open(dump_path).read())
        return -1
    if get_int(values, "nan_count") != 0:
        print("ERROR: BF-FSZ SR diff dump contains non-finite values")
        print(open(dump_path).read())
        return -1
    if get_int(values, "nonzero_projbf_fd_count") <= 0:
        print("ERROR: BF-FSZ ProjBF finite difference was vacuous")
        print(open(dump_path).read())
        return -1
    if get_int(values, "nonzero_orbital_fd_count") <= 0:
        print("ERROR: BF-FSZ orbital finite difference was vacuous")
        print(open(dump_path).read())
        return -1

    projbf_diff = get_float(values, "max_abs_projbf_fd_diff")
    orbital_diff = get_float(values, "max_abs_orbital_fd_diff")
    if projbf_diff > 1.0e-8:
        print("ERROR: BF-FSZ ProjBF finite-difference mismatch: {:.3e}".format(projbf_diff))
        print(open(dump_path).read())
        return -1
    if orbital_diff > 1.0e-8:
        print("ERROR: BF-FSZ orbital finite-difference mismatch: {:.3e}".format(orbital_diff))
        print(open(dump_path).read())
        return -1
    if check_identity:
        if get_int(values, "info_no_bf") != 0:
            print("ERROR: BF-FSZ SR diff NoBF reference calculation failed")
            print(open(dump_path).read())
            return -1
        identity_diff = get_float(values, "max_abs_identity_orbital_diff")
        if identity_diff > 1.0e-10:
            print("ERROR: BF-FSZ identity orbital O mismatch: {:.3e}".format(identity_diff))
            print(open(dump_path).read())
            return -1
    return 0


def optimization_modpara_updates(nstore=0, nsrcg=0, nsplit=1, samples=16):
    updates = {
        "NVMCCalMode": "0",
        "NSROptItrStep": "2",
        "NSROptItrSmp": "2",
        "NVMCSample": str(samples),
        "NVMCWarmUp": "4",
        "DSROptRedCut": "1.0e-10",
        "DSROptStaDel": "1.0e-2",
        "DSROptStepDt": "1.0e-2",
        "NStore": str(nstore),
        "NSRCG": str(nsrcg),
        "NSplitSize": str(nsplit),
    }
    if nsrcg != 0:
        updates["NSRCGFallback"] = "1"
        updates["NSRCGAbortOnFail"] = "0"
    return updates


def prepare_optimization_case(rootdir, name, include_backflow=True, orbital_complex_type=1,
                              orbital_optimize=True, backflow_optimize=False,
                              momentum_projection=False, nstore=0, nsrcg=0,
                              nsplit=1, samples=16):
    workdir = prepare_case(
        rootdir,
        name,
        include_backflow,
        orbital_complex_type=orbital_complex_type,
        orbital_optimize=orbital_optimize,
        backflow_optimize=backflow_optimize,
    )
    update_modpara(workdir, optimization_modpara_updates(nstore, nsrcg, nsplit, samples))
    if momentum_projection:
        update_modpara(workdir, {"NMPTrans": "2"})
        make_momentum_projection(workdir)
    return workdir


def assert_optimization_outputs(workdir, include_backflow):
    zqp_path = os.path.join(workdir, "output", "zqp_opt.dat")
    if not os.path.exists(zqp_path):
        print("ERROR: zqp_opt.dat was not created.")
        return -1
    status = assert_finite_values(read_flat_floats(zqp_path), "zqp_opt.dat")
    if status != 0:
        return status

    nslater = parse_norbitalidx(os.path.join(workdir, "orbitalidxgen.def"))
    nprojbf = build_chain_nn_backflow(length=4, optimize=False).n_proj_bf if include_backflow else 0
    expected_zqp_groups = 2 + nprojbf + nslater
    zqp_values = read_flat_floats(zqp_path)
    if len(zqp_values) != 3 * expected_zqp_groups:
        print("ERROR: zqp_opt.dat length mismatch: got {} values, expected {}".format(
            len(zqp_values), 3 * expected_zqp_groups))
        return -1
    if include_backflow:
        status = assert_child_opt_file(
            workdir,
            "zqp_bf_opt.dat",
            nprojbf,
            2,
            "ProjBF opt block",
        )
        if status != 0:
            return status
    return assert_child_opt_file(
        workdir,
        "zqp_orbital_general_opt.dat",
        nslater,
        2 + nprojbf,
        "OrbitalGeneral opt block",
    )


def run_positive_optimization_case(rootdir, case_name, mpi_procs, options):
    prep_options = dict(options)
    prep_options.pop("compare_no_bf", None)
    prep_options.pop("compare_direct_bf", None)
    workdir = prepare_optimization_case(rootdir, case_name, **prep_options)
    proc = run_vmc(rootdir, workdir, mpi_procs)
    if proc.returncode != 0:
        print(proc.stdout)
        return proc.returncode
    status = assert_optimization_outputs(workdir, include_backflow=True)
    if status != 0:
        return status

    if options.get("compare_no_bf", False):
        no_bf_options = dict(options)
        no_bf_options.pop("compare_no_bf", None)
        no_bf_options.pop("compare_direct_bf", None)
        no_bf_options["include_backflow"] = False
        no_bf_options["backflow_optimize"] = False
        no_bf_workdir = prepare_optimization_case(
            rootdir,
            case_name + "_nobf_opt_ref",
            **no_bf_options
        )
        no_bf_proc = run_vmc(rootdir, no_bf_workdir, mpi_procs)
        if no_bf_proc.returncode != 0:
            print(no_bf_proc.stdout)
            return no_bf_proc.returncode
        status = assert_optimization_outputs(no_bf_workdir, include_backflow=False)
        if status != 0:
            return status
        status = compare_child_rows(
            read_orbital_opt_rows(workdir),
            read_orbital_opt_rows(no_bf_workdir),
            1.0e-8,
            "BF-FSZ identity orbital optimization",
        )
        if status != 0:
            return status

    if options.get("compare_direct_bf", False):
        ref_options = dict(options)
        ref_options.pop("compare_no_bf", None)
        ref_options.pop("compare_direct_bf", None)
        ref_options["nstore"] = 0
        ref_options["nsrcg"] = 0
        ref_workdir = prepare_optimization_case(
            rootdir,
            case_name + "_direct_ref",
            **ref_options
        )
        ref_proc = run_vmc(rootdir, ref_workdir, mpi_procs)
        if ref_proc.returncode != 0:
            print(ref_proc.stdout)
            return ref_proc.returncode
        status = assert_optimization_outputs(ref_workdir, include_backflow=True)
        if status != 0:
            return status
        status = compare_child_rows(
            read_orbital_opt_rows(workdir),
            read_orbital_opt_rows(ref_workdir),
            1.0e-8,
            "stored-O BF-FSZ orbital optimization",
        )
        if status != 0:
            return status

    return 0


def run_all_fixed_invalid_case(rootdir, case_name, mpi_procs):
    workdir = prepare_optimization_case(
        rootdir,
        case_name,
        include_backflow=True,
        orbital_complex_type=1,
        orbital_optimize=False,
        backflow_optimize=False,
        nstore=0,
        nsrcg=0,
    )
    proc = run_vmc(rootdir, workdir, mpi_procs)
    expected = "BackFlow FSZ optimization requires at least one optimized variational parameter"
    if proc.returncode == 0:
        print("ERROR: {} unexpectedly succeeded".format(case_name))
        return -1
    if expected not in proc.stdout:
        print("ERROR: {} did not report expected error: {}".format(case_name, expected))
        print(proc.stdout)
        return -1
    if "Start: Optimize VMC parameters." in proc.stdout:
        print("ERROR: {} reached optimization loop before failing".format(case_name))
        print(proc.stdout)
        return -1
    return 0


def run_nsplit_optimization_case(rootdir, case_name, mpi_procs):
    split_ranks = int(mpi_procs) if mpi_procs else 4
    if split_ranks < 4:
        split_ranks = 4
    ref_ranks = max(1, split_ranks // 2)
    split_workdir = prepare_optimization_case(
        rootdir,
        case_name,
        include_backflow=True,
        nstore=1,
        nsrcg=0,
        nsplit=2,
    )
    split_proc = run_vmc(rootdir, split_workdir, str(split_ranks))
    if split_proc.returncode != 0:
        print(split_proc.stdout)
        return split_proc.returncode
    status = assert_optimization_outputs(split_workdir, include_backflow=True)
    if status != 0:
        return status

    ref_workdir = prepare_optimization_case(
        rootdir,
        case_name + "_ref",
        include_backflow=True,
        nstore=1,
        nsrcg=0,
        nsplit=1,
    )
    ref_proc = run_vmc(rootdir, ref_workdir, str(ref_ranks))
    if ref_proc.returncode != 0:
        print(ref_proc.stdout)
        return ref_proc.returncode
    status = assert_optimization_outputs(ref_workdir, include_backflow=True)
    if status != 0:
        return status
    return compare_child_rows(
        read_orbital_opt_rows(split_workdir),
        read_orbital_opt_rows(ref_workdir),
        1.0e-8,
        "NSplitSize BF-FSZ orbital optimization",
    )


def run_optimization_case(rootdir, case_name, mpi_procs=None):
    optimization_cases = {
        "BackFlow_FSZ_Optimization_Identity_Complex": {
            "orbital_complex_type": 1,
            "compare_no_bf": True,
        },
        "BackFlow_FSZ_Optimization_Identity_Complex_mpi": {
            "orbital_complex_type": 1,
            "compare_no_bf": True,
        },
        "BackFlow_FSZ_Optimization_Identity_Real": {
            "orbital_complex_type": 0,
            "compare_no_bf": True,
        },
        "BackFlow_FSZ_Optimization_MomentumProjection_Complex": {
            "orbital_complex_type": 1,
            "momentum_projection": True,
            "compare_no_bf": True,
        },
        "BackFlow_FSZ_Optimization_MomentumProjection_Complex_mpi": {
            "orbital_complex_type": 1,
            "momentum_projection": True,
            "compare_no_bf": True,
        },
        "BackFlow_FSZ_Optimization_BackFlowParams_Complex": {
            "orbital_complex_type": 1,
            "backflow_optimize": True,
        },
        "BackFlow_FSZ_Optimization_StoredO_Complex": {
            "orbital_complex_type": 1,
            "nstore": 1,
            "compare_direct_bf": True,
        },
        "BackFlow_FSZ_Optimization_SRCG_Complex": {
            "orbital_complex_type": 1,
            "nstore": 1,
            "nsrcg": 1,
        },
    }
    if case_name == "BackFlow_FSZ_Optimization_AllFixed_Invalid":
        return run_all_fixed_invalid_case(rootdir, case_name, mpi_procs)
    if case_name == "BackFlow_FSZ_Optimization_NSplitSize_mpi":
        return run_nsplit_optimization_case(rootdir, case_name, mpi_procs)
    if case_name not in optimization_cases:
        return None

    options = {
        "include_backflow": True,
        "orbital_complex_type": 1,
        "orbital_optimize": True,
        "backflow_optimize": False,
        "momentum_projection": False,
        "nstore": 0,
        "nsrcg": 0,
        "nsplit": 1,
        "samples": 16,
    }
    options.update(optimization_cases[case_name])
    return run_positive_optimization_case(rootdir, case_name, mpi_procs, options)


def run_spin_changing_optimization_case(rootdir, case_name, mpi_procs=None):
    if case_name != "BackFlow_FSZ_SpinChanging_C_Optimization_NonIdentity_Complex":
        return None
    workdir = prepare_optimization_case(
        rootdir,
        case_name,
        include_backflow=True,
        orbital_complex_type=1,
        orbital_optimize=True,
        backflow_optimize=True,
        nstore=0,
        nsrcg=0,
        samples=16,
    )
    update_modpara(workdir, {"2Sz": "-1"})
    write_spin_changing_c2_defs(workdir)
    init_path = write_nonidentity_init(workdir)
    proc = run_vmc(rootdir, workdir, mpi_procs=mpi_procs, init_path=init_path)
    if proc.returncode != 0:
        print(proc.stdout)
        return proc.returncode
    return assert_optimization_outputs(workdir, include_backflow=True)


def expect_invalid(rootdir, name, updates, expected, mpi_procs=None, local_sites=None, mutate_defs=None):
    workdir = prepare_case(rootdir, name, True)
    update_modpara(workdir, updates)
    if local_sites is not None:
        write_locspn(workdir, local_sites)
    if mutate_defs is not None:
        mutate_defs(workdir)
    proc = run_vmc(rootdir, workdir, mpi_procs)
    if proc.returncode == 0:
        print("ERROR: {} unexpectedly succeeded".format(name))
        return -1
    if expected not in proc.stdout:
        print("ERROR: {} did not report expected error: {}".format(name, expected))
        print(proc.stdout)
        return -1
    if "Start: Sampling." in proc.stdout:
        print("ERROR: {} reached sampling before failing".format(name))
        print(proc.stdout)
        return -1
    return 0


def get_named_invalid_case(case_name):
    invalid_cases = {
        "BackFlow_FSZ_InvalidSpinChangingTransfer": (
            {},
            "BackFlow FSZ supports only spin-conserving Transfer terms",
            None,
            make_spin_changing_transfer,
        ),
        "BackFlow_FSZ_InvalidSpinChangingOneBodyG": (
            {},
            "BackFlow FSZ supports only spin-conserving OneBodyG terms",
            None,
            make_spin_changing_one_body_g,
        ),
        "BackFlow_FSZ_InvalidSpinChangingOneBodyG_mpi": (
            {},
            "BackFlow FSZ supports only spin-conserving OneBodyG terms",
            None,
            make_spin_changing_one_body_g,
        ),
        "BackFlow_FSZ_InvalidSpinChangingTwoBodyG": (
            {},
            "BackFlow FSZ supports only spin-conserving TwoBodyG terms",
            None,
            make_spin_changing_two_body_g,
        ),
        "BackFlow_FSZ_InvalidSpinChangingTwoBodyGEx": (
            {},
            "including entries derived from TwoBodyGEx",
            None,
            make_spin_changing_two_body_g_ex,
        ),
    }
    return invalid_cases.get(case_name)


def assert_spin_changing_c1_counters(workdir, expect_accept):
    counters = read_sampling_counters(
        os.path.join(workdir, "output", "zvo_time_001.dat"),
    )
    if counters["n_hop"] <= 0 or counters["n_lsf"] <= 0:
        print("ERROR: spin-changing sampler did not propose both hop and local spin flip: {}".format(
            counters))
        return -1
    if expect_accept:
        if counters["acc_hop"] <= 0.0 or counters["acc_lsf"] <= 0.0:
            print("ERROR: spin-changing sampler did not accept both proposal classes: {}".format(
                counters))
            return -1
    elif counters["acc_hop"] != 0.0 or counters["acc_lsf"] != 0.0:
        print("ERROR: forced-reject spin-changing sampler accepted a proposal: {}".format(
            counters))
        return -1
    return 0


def assert_spin_changing_one_body_nonzero(workdir):
    rows = read_float_rows(
        os.path.join(workdir, "output", "zvo_cisajs_001.dat"),
    )
    spin_changing_rows = rows[1:5]
    max_abs = max(abs(value) for row in spin_changing_rows for value in row[-2:])
    if not math.isfinite(max_abs) or max_abs <= 1.0e-12:
        print("ERROR: spin-changing OneBodyG result was vacuous")
        return -1
    return 0


def run_spin_changing_c1_case(rootdir, case_name, mpi_procs=None):
    cases = {
        "BackFlow_FSZ_SpinChanging_C1_Identity_Complex": (True, False, False, False),
        "BackFlow_FSZ_SpinChanging_C1_Identity_Complex_mpi": (True, False, False, False),
        "BackFlow_FSZ_SpinChanging_C1_Identity_Complex_omp": (True, False, False, False),
        "BackFlow_FSZ_SpinChanging_C1_Identity_Complex_omp_nested_off": (True, False, False, False),
        "BackFlow_FSZ_SpinChanging_C1_MomentumProjection_Complex": (True, True, False, False),
        "BackFlow_FSZ_SpinChanging_C1_MomentumProjection_NonIdentity_Complex": (
            False, True, False, False,
        ),
        "BackFlow_FSZ_SpinChanging_C1_NonIdentity_Complex_mpi": (False, False, False, False),
        "BackFlow_FSZ_SpinChanging_C1_Reject_NonIdentity_Complex": (False, False, True, False),
        "BackFlow_FSZ_SpinChanging_C1_RankFallback_NonIdentity_Complex_mpi": (
            False, True, False, True,
        ),
    }
    if case_name not in cases:
        return None

    compare_no_bf, use_momentum, force_reject, rank_fallback = cases[case_name]
    bf_workdir = prepare_case(rootdir, case_name, True)
    update_modpara(bf_workdir, {"2Sz": "-1"})
    if mpi_procs:
        update_modpara(bf_workdir, {"NSplitSize": str(mpi_procs)})
    write_spin_changing_c1_defs(bf_workdir)
    if use_momentum:
        update_modpara(bf_workdir, {"NMPTrans": "2"})
        make_momentum_projection(bf_workdir)

    init_path = None if compare_no_bf else write_nonidentity_init(bf_workdir)
    bf_env = {
        "MVMC_BF_PROFILE": "1",
        "MVMC_BF_FSZ_GREEN_REBUILD_CHECK": "1",
        "MVMC_BF_FSZ_AFFECTED_CHECK": "1",
        "MVMC_BF_FSZ_MATRIX_FREE_CHECK": "1",
        "MVMC_BF_FSZ_PF_UPDATE_CHECK": "1",
        "MVMC_BF_FSZ_INV_UPDATE_CHECK": "1",
    }
    if force_reject:
        bf_env["MVMC_BF_FSZ_SAMPLING_REJECT_CHECK"] = "1"
    if rank_fallback:
        bf_env["MVMC_BF_FSZ_INV_UPDATE_INJECT_STAGE"] = "1"
        bf_env["MVMC_BF_FSZ_INV_UPDATE_INJECT_RANK"] = "1"

    bf_proc = run_vmc(
        rootdir,
        bf_workdir,
        mpi_procs=mpi_procs,
        init_path=init_path,
        extra_env=bf_env,
    )
    if bf_proc.returncode != 0:
        print(bf_proc.stdout)
        return bf_proc.returncode

    status = assert_spin_changing_c1_counters(bf_workdir, not force_reject)
    if status != 0:
        return status

    timer_path = os.path.join(bf_workdir, "output", "zvo_CalcTimer.dat")
    if force_reject:
        inv_paths = read_bffsz_inv_paths(timer_path)
        commits = read_bffsz_sample_commits(timer_path)
        path_names = ("optimized", "direct-full", "fallback")
        if sum(inv_paths[name] for name in path_names) != 0 \
                or sum(commits[name] for name in path_names) != 0:
            print("ERROR: forced-reject spin-changing proposal committed matrix state")
            return -1
        return 0

    for filename, label in (
        ("zvo_out_001.dat", "spin-changing Hamiltonian"),
        ("zvo_cisajs_001.dat", "spin-changing OneBodyG"),
        ("zvo_cisajscktalt_001.dat", "C1 spin-conserving TwoBodyG"),
    ):
        status = assert_finite_nonzero_rows(
            os.path.join(bf_workdir, "output", filename), label,
        )
        if status != 0:
            return status
    status = assert_spin_changing_one_body_nonzero(bf_workdir)
    if status != 0:
        return status

    if rank_fallback:
        inv_paths = read_bffsz_inv_paths(timer_path)
        commits = read_bffsz_sample_commits(timer_path)
        if inv_paths["fallback"] <= 0 or inv_paths["optimized"] != 0:
            print("ERROR: rank-specific spin-changing inverse fallback was not collective")
            return -1
        if commits["fallback"] != inv_paths["fallback"]:
            print("ERROR: rank-specific spin-changing fallback commit count mismatch")
            return -1

    if not compare_no_bf:
        return 0

    no_bf_workdir = prepare_case(rootdir, case_name + "_nobf", False)
    update_modpara(no_bf_workdir, {"2Sz": "-1"})
    if mpi_procs:
        update_modpara(no_bf_workdir, {"NSplitSize": str(mpi_procs)})
    write_spin_changing_c1_defs(no_bf_workdir)
    if use_momentum:
        update_modpara(no_bf_workdir, {"NMPTrans": "2"})
        make_momentum_projection(no_bf_workdir)
    no_bf_proc = run_vmc(rootdir, no_bf_workdir, mpi_procs=mpi_procs)
    if no_bf_proc.returncode != 0:
        print(no_bf_proc.stdout)
        return no_bf_proc.returncode
    status = assert_spin_changing_c1_counters(no_bf_workdir, True)
    if status != 0:
        return status

    for filename, label in (
        ("zvo_out_001.dat", "spin-changing energy"),
        ("zvo_cisajs_001.dat", "spin-changing OneBodyG"),
        ("zvo_cisajscktalt_001.dat", "C1 TwoBodyG"),
    ):
        bf_rows = read_float_rows(os.path.join(bf_workdir, "output", filename))
        no_bf_rows = read_float_rows(os.path.join(no_bf_workdir, "output", filename))
        diff = max_abs_diff(bf_rows, no_bf_rows)
        if diff > 1.0e-10:
            print("ERROR: BackFlow FSZ identity {} mismatch: max_abs_diff={:.3e}".format(
                label, diff))
            return -1
    return 0


def assert_spin_changing_c2_rows(workdir):
    rows = read_float_rows(
        os.path.join(workdir, "output", "zvo_cisajscktalt_001.dat"),
    )
    if len(rows) != 15:
        print("ERROR: C2 Green2 class row count mismatch: {}".format(len(rows)))
        return -1
    for index in (2, 5, 6, 7, 12):
        if max(abs(value) for value in rows[index][-2:]) > 1.0e-12:
            print("ERROR: C2 structural-zero class {} was nonzero".format(index + 1))
            return -1
    true_two_body = max(abs(value) for value in rows[14][-2:])
    if not math.isfinite(true_two_body) or true_two_body <= 1.0e-12:
        print("ERROR: C2 true two-particle Green2 path was vacuous")
        return -1
    return 0


def read_c2_detail_profile(timer_path):
    with open(timer_path) as fp:
        lines = [line.strip() for line in fp]
    begin = "BF_FSZ_C2_DETAIL_PROFILE_BEGIN"
    end = "BF_FSZ_C2_DETAIL_PROFILE_END"
    if not any(line.startswith(begin) for line in lines):
        return []
    records = []
    in_section = False
    for line in lines:
        if line.startswith(begin):
            in_section = True
            continue
        if line == end:
            return records
        if not in_section or not line:
            continue
        parts = line.split()
        record = {}
        if len(parts) > 1 and "=" not in parts[1]:
            record["kind"] = parts[1]
        for part in parts:
            if "=" in part:
                key, value = part.split("=", 1)
                record[key] = value
        if parts[0] == "affected_gate":
            record["kind"] = "gate"
        elif "timer41_seconds_rank0" in record:
            record["kind"] = "total"
        elif "ordered_descriptors" in record:
            record["kind"] = "ordered_descriptors"
        records.append(record)
    raise RuntimeError("unterminated BF-FSZ C2 detail profile section")


def get_c2_detail_record(records, **query):
    matches = [
        record for record in records
        if all(record.get(key) == str(value) for key, value in query.items())
    ]
    if len(matches) != 1:
        raise RuntimeError("C2 detail record mismatch for {}: {}".format(query, matches))
    return matches[0]


def read_stable_bf_profile_lines(timer_path):
    stable = []
    with open(timer_path) as fp:
        for line in fp:
            stripped = " ".join(line.split())
            if not stripped.startswith("BF"):
                continue
            if "seconds" in stripped or "checks" in stripped:
                continue
            if ("[9" in stripped or " calls=" in stripped
                    or " hist " in stripped or " paths " in stripped
                    or " materialize " in stripped or " commits " in stripped):
                stable.append(stripped)
    return stable


def assert_files_byte_identical(left_workdir, right_workdir, filenames):
    for filename in filenames:
        left_path = os.path.join(left_workdir, "output", filename)
        right_path = os.path.join(right_workdir, "output", filename)
        with open(left_path, "rb") as fp:
            left_data = fp.read()
        with open(right_path, "rb") as fp:
            right_data = fp.read()
        if left_data != right_data:
            print("ERROR: C2 detail profile changed {}".format(filename))
            return -1
    return 0


def validate_c2_detail_profile(timer_path):
    records = read_c2_detail_profile(timer_path)
    if not records:
        print("ERROR: BF-FSZ C2 detail profile section is missing")
        return -1
    sources = ("measurement", "pair_hop", "exchange", "inter_all")
    components = (
        "dispatch", "state_projection", "bf_count", "candidate_build",
        "pfaffian", "restore", "affected_collect",
    )
    component_seconds = {}
    evaluated_total = 0
    for source in sources:
        class_calls = [
            int(get_c2_detail_record(
                records, source=source, **{"class": class_id},
            )["calls"])
            for class_id in range(1, 16)
        ]
        if sum(class_calls) <= 0 or class_calls[14] <= 0:
            print("ERROR: C2 detail source {} was vacuous".format(source))
            return -1
        if source == "measurement":
            base_calls = class_calls[0]
            expected_calls = [base_calls * class_id for class_id in range(1, 16)]
            if base_calls <= 0 or class_calls != expected_calls:
                print("ERROR: C2 15-class counter oracle mismatch: {}".format(class_calls))
                return -1

        outcomes = {
            name: int(get_c2_detail_record(
                records, source=source, outcome=name,
            )["calls"])
            for name in ("occupancy_zero", "sector_zero", "evaluated")
        }
        if sum(outcomes.values()) != class_calls[14]:
            print("ERROR: C2 {} true outcome count mismatch".format(source))
            return -1
        evaluated = outcomes["evaluated"]
        evaluated_total += evaluated

        paths = {
            name: int(get_c2_detail_record(
                records, source=source, path=name,
            )["calls"])
            for name in (
                "legacy_full", "optimized_row", "direct_full", "fallback",
                "debug_oracle",
            )
        }
        if paths["legacy_full"] != evaluated \
                or sum(paths.values()) != evaluated:
            print("ERROR: C2 {} legacy path count mismatch".format(source))
            return -1
        descriptors = int(get_c2_detail_record(
            records, source=source, kind="ordered_descriptors",
        )["ordered_descriptors"])
        if descriptors != class_calls[14]:
            print("ERROR: C2 {} descriptor count mismatch".format(source))
            return -1

        changed = get_c2_detail_record(records, source=source, kind="changed")
        affected = get_c2_detail_record(records, source=source, kind="affected")
        if int(changed["calls"]) != evaluated or int(affected["calls"]) != evaluated:
            print("ERROR: C2 {} affected call count mismatch".format(source))
            return -1
        if int(affected["at_or_above_k_full"]) != 0 \
                or (evaluated > 0 and int(affected["max"]) <= 0):
            print("ERROR: C2 {} affected gate failed".format(source))
            return -1
        for kind in ("changed_hist", "affected_hist"):
            hist_sum = sum(
                int(get_c2_detail_record(
                    records, source=source, kind=kind, bin=bin_id,
                )["calls"])
                for bin_id in range(22)
            )
            if hist_sum != evaluated:
                print("ERROR: C2 {} {} count mismatch".format(source, kind))
                return -1

        component_seconds[source] = {}
        for component in components:
            seconds = float(get_c2_detail_record(
                records, source=source, component=component,
            )["seconds_rank0"])
            if not math.isfinite(seconds) or seconds < 0.0:
                print("ERROR: C2 {} {} timer is invalid".format(source, component))
                return -1
            component_seconds[source][component] = seconds
        if sum(component_seconds[source].values()) <= 0.0:
            print("ERROR: C2 {} component timers were vacuous".format(source))
            return -1

    gate = get_c2_detail_record(records, kind="gate")
    if int(gate["k_full"]) != 32 or int(gate["evaluated_calls"]) != evaluated_total \
            or int(gate["at_or_above_k_full"]) != 0 or int(gate["pass"]) != 1:
        print("ERROR: C2 affected gate summary mismatch")
        return -1

    term_seconds = {}
    for term in ("number", "transfer", "pair_hop", "exchange", "inter_all"):
        seconds = float(get_c2_detail_record(
            records, hamiltonian_term=term,
        )["seconds_rank0"])
        if not math.isfinite(seconds) or seconds < 0.0:
            print("ERROR: C2 Hamiltonian term timer {} is invalid".format(term))
            return -1
        term_seconds[term] = seconds
    for source in ("pair_hop", "exchange", "inter_all"):
        if term_seconds[source] + 5.0e-6 < sum(component_seconds[source].values()):
            print("ERROR: C2 {} component time exceeds enclosing term".format(source))
            return -1

    total = get_c2_detail_record(records, kind="total")
    timer41 = float(total["timer41_seconds_rank0"])
    term_total = float(total["hamiltonian_term_seconds_rank0"])
    sz_seconds = float(total["sz_seconds_rank0"])
    wrapper = float(total["wrapper_overhead_seconds_rank0"])
    if abs(term_total - sum(term_seconds.values())) > 5.0e-6 \
            or abs(timer41 - term_total - sz_seconds - wrapper) > 5.0e-6 \
            or wrapper < -5.0e-6:
        print("ERROR: C2 timer41/term/Sz/wrapper consistency failed")
        return -1
    return 0


def run_c2_detail_profile_case(rootdir, case_name, mpi_procs=None):
    cases = (
        "BackFlow_FSZ_C2_Detail_Profile_Complex",
        "BackFlow_FSZ_C2_Detail_Profile_Complex_mpi",
        "BackFlow_FSZ_C2_Detail_Profile_Complex_omp",
    )
    if case_name not in cases:
        return None

    run_specs = (
        ("off", {}),
        ("new", {
            "MVMC_BF_FSZ_C2_DETAIL_PROFILE": "1",
            "MVMC_BF_FSZ_PF_UPDATE_KFULL": "0",
        }),
        ("old", {"MVMC_BF_PROFILE": "1"}),
        ("both", {
            "MVMC_BF_PROFILE": "1",
            "MVMC_BF_FSZ_C2_DETAIL_PROFILE": "1",
            "MVMC_BF_FSZ_PF_UPDATE_KFULL": "33",
        }),
    )
    workdirs = {}
    for suffix, extra_env in run_specs:
        workdir = prepare_case(rootdir, case_name + "_" + suffix, True)
        update_modpara(workdir, {"2Sz": "-1", "NVMCSample": "16"})
        if mpi_procs:
            update_modpara(workdir, {"NSplitSize": str(mpi_procs)})
        write_c2_detail_profile_defs(workdir)
        proc = run_vmc(
            rootdir, workdir, mpi_procs=mpi_procs, extra_env=extra_env,
        )
        if proc.returncode != 0:
            print(proc.stdout)
            return proc.returncode
        workdirs[suffix] = workdir

    physical_files = (
        "zvo_out_001.dat", "zvo_var_001.dat", "zvo_cisajs_001.dat",
        "zvo_cisajscktalt_001.dat", "zvo_cisajscktaltex_001.dat",
    )
    status = assert_files_byte_identical(
        workdirs["off"], workdirs["new"], physical_files,
    )
    if status != 0:
        return status

    timer_paths = {
        suffix: os.path.join(workdir, "output", "zvo_CalcTimer.dat")
        for suffix, workdir in workdirs.items()
    }
    timer_text = {}
    for suffix, path in timer_paths.items():
        with open(path) as fp:
            timer_text[suffix] = fp.read()
    detail_marker = "BF_FSZ_C2_DETAIL_PROFILE_BEGIN"
    old_marker = "BF profile counters (MVMC_BF_PROFILE=1)"
    if detail_marker in timer_text["off"] or old_marker in timer_text["off"] \
            or detail_marker not in timer_text["new"] or old_marker in timer_text["new"] \
            or detail_marker in timer_text["old"] or old_marker not in timer_text["old"] \
            or detail_marker not in timer_text["both"] or old_marker not in timer_text["both"]:
        print("ERROR: old/new BF profile enable sections are not independent")
        return -1
    if read_stable_bf_profile_lines(timer_paths["old"]) \
            != read_stable_bf_profile_lines(timer_paths["both"]):
        print("ERROR: C2 detail profile changed existing BF profile counters")
        return -1
    for suffix in ("new", "both"):
        status = validate_c2_detail_profile(timer_paths[suffix])
        if status != 0:
            return status
    return 0


def run_spin_changing_c2_case(rootdir, case_name, mpi_procs=None):
    cases = {
        "BackFlow_FSZ_SpinChanging_C2_Identity_Complex": (True, False, False),
        "BackFlow_FSZ_SpinChanging_C2_Identity_Complex_mpi": (True, False, False),
        "BackFlow_FSZ_SpinChanging_C2_Identity_Complex_omp": (True, False, False),
        "BackFlow_FSZ_SpinChanging_C2_MomentumProjection_Complex": (True, True, False),
        "BackFlow_FSZ_SpinChanging_C2_MomentumProjection_NonIdentity_Complex": (
            False, True, False,
        ),
        "BackFlow_FSZ_SpinChanging_C2_Order_NonIdentity_Complex": (False, False, True),
    }
    if case_name not in cases:
        return None

    compare_no_bf, use_momentum, compare_order = cases[case_name]
    bf_workdir = prepare_case(rootdir, case_name, True)
    update_modpara(bf_workdir, {"2Sz": "-1", "NVMCSample": "64"})
    if mpi_procs:
        update_modpara(bf_workdir, {"NSplitSize": str(mpi_procs)})
    two_body_rows = write_spin_changing_c2_defs(bf_workdir)
    if use_momentum:
        update_modpara(bf_workdir, {"NMPTrans": "2"})
        make_momentum_projection(bf_workdir)
    init_path = None if compare_no_bf else write_nonidentity_init(bf_workdir)
    bf_env = {
        "MVMC_BF_FSZ_GREEN_REBUILD_CHECK": "1",
        "MVMC_BF_FSZ_AFFECTED_CHECK": "1",
        "MVMC_BF_FSZ_MATRIX_FREE_CHECK": "1",
    }
    bf_proc = run_vmc(
        rootdir,
        bf_workdir,
        mpi_procs=mpi_procs,
        init_path=init_path,
        extra_env=bf_env,
    )
    if bf_proc.returncode != 0:
        print(bf_proc.stdout)
        return bf_proc.returncode
    status = assert_spin_changing_c1_counters(bf_workdir, True)
    if status != 0:
        return status
    status = assert_spin_changing_one_body_nonzero(bf_workdir)
    if status != 0:
        return status
    status = assert_spin_changing_c2_rows(bf_workdir)
    if status != 0:
        return status

    if compare_order:
        reference_workdir = prepare_case(rootdir, case_name + "_reference", True)
        update_modpara(reference_workdir, {"2Sz": "-1", "NVMCSample": "64"})
        reference_rows = write_spin_changing_c2_defs(
            reference_workdir, reverse_two_body=True,
        )
        reference_init = write_nonidentity_init(reference_workdir)
        reference_proc = run_vmc(
            rootdir,
            reference_workdir,
            init_path=reference_init,
            extra_env=bf_env,
        )
        if reference_proc.returncode != 0:
            print(reference_proc.stdout)
            return reference_proc.returncode
        ordered_values = read_float_rows(
            os.path.join(bf_workdir, "output", "zvo_cisajscktalt_001.dat"),
        )
        reference_values = read_float_rows(
            os.path.join(reference_workdir, "output", "zvo_cisajscktalt_001.dat"),
        )
        ordered_by_term = dict(zip(two_body_rows, ordered_values))
        reference_by_term = dict(zip(reference_rows, reference_values))
        diff = max_abs_diff(
            [ordered_by_term[row][-2:] for row in two_body_rows],
            [reference_by_term[row][-2:] for row in two_body_rows],
        )
        if diff > 1.0e-12:
            print("ERROR: C2 Green2 depends on term order: max_abs_diff={:.3e}".format(diff))
            return -1
        ordered_energy = read_first_row(
            os.path.join(bf_workdir, "output", "zvo_out_001.dat"),
        )
        reference_energy = read_first_row(
            os.path.join(reference_workdir, "output", "zvo_out_001.dat"),
        )
        if max_abs_diff([ordered_energy], [reference_energy]) > 1.0e-12:
            print("ERROR: C2 Hamiltonian changed after Green2 term reordering")
            return -1
        return 0

    if not compare_no_bf:
        return 0

    no_bf_workdir = prepare_case(rootdir, case_name + "_nobf", False)
    update_modpara(no_bf_workdir, {"2Sz": "-1", "NVMCSample": "64"})
    if mpi_procs:
        update_modpara(no_bf_workdir, {"NSplitSize": str(mpi_procs)})
    write_spin_changing_c2_defs(no_bf_workdir)
    if use_momentum:
        update_modpara(no_bf_workdir, {"NMPTrans": "2"})
        make_momentum_projection(no_bf_workdir)
    no_bf_proc = run_vmc(rootdir, no_bf_workdir, mpi_procs=mpi_procs)
    if no_bf_proc.returncode != 0:
        print(no_bf_proc.stdout)
        return no_bf_proc.returncode
    status = assert_spin_changing_c2_rows(no_bf_workdir)
    if status != 0:
        return status

    for filename, label in (
        ("zvo_out_001.dat", "C2 two-body Hamiltonian"),
        ("zvo_cisajs_001.dat", "C2 OneBodyG"),
        ("zvo_cisajscktaltex_001.dat", "C2 TwoBodyGEx"),
        ("zvo_cisajscktalt_001.dat", "C2 Green2 classes"),
    ):
        bf_rows = read_float_rows(os.path.join(bf_workdir, "output", filename))
        no_bf_rows = read_float_rows(os.path.join(no_bf_workdir, "output", filename))
        diff = max_abs_diff(bf_rows, no_bf_rows)
        if diff > 1.0e-10:
            print("ERROR: BackFlow FSZ identity {} mismatch: max_abs_diff={:.3e}".format(
                label, diff))
            return -1
    return 0


def run_c2_nonfsz_invalid_case(rootdir, case_name, mpi_procs=None):
    if case_name != "BackFlow_InvalidTwoBodyHamiltonian_NonFSZ":
        return None
    refdir = os.path.join(rootdir, "data", "BackFlow_Identity_Complex")
    workdir = os.path.join(rootdir, "work", case_name)
    if os.path.exists(workdir):
        shutil.rmtree(workdir)
    os.makedirs(workdir)
    for filename in os.listdir(refdir):
        source = os.path.join(refdir, filename)
        if os.path.isfile(source):
            shutil.copy(source, os.path.join(workdir, filename))
    write_chain_nn_backflow(workdir, length=4, optimize=False)
    with open(os.path.join(workdir, "pairhop.def"), "w") as fp:
        fp.write("=============================================\n")
        fp.write("NPairHopp          1\n")
        fp.write("=============================================\n")
        fp.write("====== Pair-Hopping term ====================\n")
        fp.write("=============================================\n")
        fp.write("    0     1          0.370000000000000\n")
    append_namelist_entry(workdir, "PairHop", "pairhop.def")
    proc = run_vmc(rootdir, workdir, mpi_procs=mpi_procs)
    expected = "BackFlow MVP does not support two-body Hamiltonian terms"
    if proc.returncode == 0:
        print("ERROR: non-FSZ BackFlow two-body Hamiltonian unexpectedly succeeded")
        return -1
    if expected not in proc.stdout:
        print("ERROR: non-FSZ BackFlow two-body Hamiltonian did not report expected error")
        print(proc.stdout)
        return -1
    if "Start: Sampling." in proc.stdout:
        print("ERROR: non-FSZ BackFlow two-body Hamiltonian reached sampling")
        return -1
    return 0


def main():
    case_name = sys.argv[1] if len(sys.argv) > 1 else "BackFlow_FSZ_IdentityEnergy_Complex"
    rootdir = os.getcwd()
    mpi_procs = os.environ.get("MVMC_MPI_PROCS")
    momentum_projection_cases = (
        "BackFlow_FSZ_MomentumProjection_Complex",
        "BackFlow_FSZ_MomentumProjection_Complex_mpi",
        "BackFlow_FSZ_MomentumProjection_NonIdentity_Complex",
    )
    nonidentity_momentum_case = case_name == "BackFlow_FSZ_MomentumProjection_NonIdentity_Complex"
    named_invalid = get_named_invalid_case(case_name)
    c1_status = run_spin_changing_c1_case(rootdir, case_name, mpi_procs)
    if c1_status is not None:
        return c1_status
    c2_status = run_spin_changing_c2_case(rootdir, case_name, mpi_procs)
    if c2_status is not None:
        return c2_status
    c2_profile_status = run_c2_detail_profile_case(rootdir, case_name, mpi_procs)
    if c2_profile_status is not None:
        return c2_profile_status
    c2_invalid_status = run_c2_nonfsz_invalid_case(rootdir, case_name, mpi_procs)
    if c2_invalid_status is not None:
        return c2_invalid_status
    stale_base_status = run_twobody_stale_base_case(rootdir, case_name, mpi_procs)
    if stale_base_status is not None:
        return stale_base_status
    sr_diff_status = run_sr_diff_case(rootdir, case_name, mpi_procs)
    if sr_diff_status is not None:
        return sr_diff_status
    optimization_status = run_optimization_case(rootdir, case_name, mpi_procs)
    if optimization_status is not None:
        return optimization_status
    spin_optimization_status = run_spin_changing_optimization_case(
        rootdir, case_name, mpi_procs,
    )
    if spin_optimization_status is not None:
        return spin_optimization_status
    if named_invalid is not None:
        updates, expected, local_sites, mutate_defs = named_invalid
        return expect_invalid(rootdir, case_name, updates, expected, mpi_procs, local_sites, mutate_defs)

    bf_workdir = prepare_case(rootdir, case_name, True)
    no_bf_workdir = prepare_case(rootdir, case_name + "_nobf", False)
    if case_name in momentum_projection_cases:
        for workdir in (bf_workdir, no_bf_workdir):
            update_modpara(workdir, {"NMPTrans": "2"})
            make_momentum_projection(workdir)
    init_path = write_nonidentity_init(bf_workdir) if nonidentity_momentum_case else None

    bf_proc = run_vmc(rootdir, bf_workdir, mpi_procs, init_path)
    if bf_proc.returncode != 0:
        print(bf_proc.stdout)
        return bf_proc.returncode
    if nonidentity_momentum_case:
        for filename, label in (
            ("zvo_out_001.dat", "zvo_out"),
            ("zvo_cisajs_001.dat", "OneBodyG"),
            ("zvo_cisajscktalt_001.dat", "TwoBodyG"),
        ):
            status = assert_finite_nonzero_rows(os.path.join(bf_workdir, "output", filename), label)
            if status != 0:
                return status
        return 0

    no_bf_proc = run_vmc(rootdir, no_bf_workdir, mpi_procs)
    if no_bf_proc.returncode != 0:
        print(no_bf_proc.stdout)
        return no_bf_proc.returncode

    bf_row = read_first_row(os.path.join(bf_workdir, "output", "zvo_out_001.dat"))
    no_bf_row = read_first_row(os.path.join(no_bf_workdir, "output", "zvo_out_001.dat"))
    if len(bf_row) != len(no_bf_row):
        print("ERROR: zvo_out column mismatch: bf={} no_bf={}".format(len(bf_row), len(no_bf_row)))
        return -1

    max_diff = max(abs(x - y) for x, y in zip(bf_row, no_bf_row))
    if max_diff > 1.0e-10:
        print("ERROR: BackFlow FSZ identity energy mismatch: max_abs_diff={:.3e}".format(max_diff))
        print("bf    {}".format(bf_row))
        print("no-bf {}".format(no_bf_row))
        return -1

    comparisons = [
        ("zvo_cisajs_001.dat", "OneBodyG"),
        ("zvo_cisajscktalt_001.dat", "TwoBodyG"),
    ]
    for filename, label in comparisons:
        bf_rows = read_float_rows(os.path.join(bf_workdir, "output", filename))
        no_bf_rows = read_float_rows(os.path.join(no_bf_workdir, "output", filename))
        diff = max_abs_diff(bf_rows, no_bf_rows)
        if diff > 1.0e-10:
            print("ERROR: BackFlow FSZ identity {} mismatch: max_abs_diff={:.3e}".format(label, diff))
            return -1

    invalid_cases = [
        (
            case_name + "_InvalidLocSpin",
            {"NExUpdatePath": "1"},
            "BackFlow MVP does not support NLocalSpin > 0",
            [0],
        ),
    ]
    for name, updates, expected, local_sites in invalid_cases:
        status = expect_invalid(rootdir, name, updates, expected, mpi_procs, local_sites)
        if status != 0:
            return status

    return 0


if __name__ == "__main__":
    sys.exit(main())
