name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1,15 * *' # JST 9:00 on 1st and 15th every month

jobs:
  ctest:
    runs-on: ${{ matrix.os }}

    name: "OS: ${{ matrix.os }}, mpitest: ${{ matrix.mpi }}, OMP: ${{ matrix.ompsize }}"

    strategy:
      matrix:
        os: ["ubuntu-latest"]
        mpi: [true, false]
        ompsize: [1, 4]
        include:
          - os: "macos-latest"
            mpi: false
            ompsize: 1
        exclude:
          - os: "ubuntu-latest"
            mpi: true
            ompsize: 4
      fail-fast: false

    env:
      OMP_NUM_THREADS: ${{ matrix.ompsize }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: apt
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt update
          sudo apt install liblapack-dev openmpi-bin libopenmpi-dev libscalapack-openmpi-dev

      - name: brew
        if: ${{ runner.os == 'macOS' }}
        run: |
          brew install openmpi scalapack libomp blis

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.11"

      - name: pip
        run: |
          python3 -m pip install numpy jsonschema

      - name: make workspace
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: cmake
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: |
          cmake --version
          if [ ${{ runner.os }} = "macOS" ] ; then
            # CONFIG=apple requires gfortran but macOS runner has not, but gfortran-11, 12, ...
            cmake -DCONFIG=apple -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_Fortran_COMPILER=gfortran-14 $GITHUB_WORKSPACE
          else
            cmake -DCMAKE_VERBOSE_MAKEFILE=ON $GITHUB_WORKSPACE
          fi

      - name: build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build ./ -j4

      - name: ctest without MPI
        if: ${{ matrix.mpi == false }}
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: |
          if [ ${{ matrix.ompsize }} == 1 ]; then
            ctest --parallel 4 --output-on-failure -E '_mpi$'
          else
            ctest --output-on-failure -E '_mpi$'
          fi

      - name: ctest with MPI
        if: ${{ matrix.mpi == true }}
        working-directory: ${{runner.workspace}}/build
        shell: bash
        env:
          OMPI_MCA_rmaps_base_oversubscribe: "1"
        run: ctest --output-on-failure -R '_mpi$'
